// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/resolutions.proto

#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_resolutions_connection.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_resolutions_connection_impl.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_resolutions_option_defaults.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_resolutions_stub_factory.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_resolutions_options.h"
#include "google/cloud/background_threads.h"
#include "google/cloud/common_options.h"
#include "google/cloud/credentials.h"
#include "google/cloud/grpc_options.h"
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

IssuerSwitchResolutionsConnection::~IssuerSwitchResolutionsConnection() =
    default;

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Complaint>>
IssuerSwitchResolutionsConnection::CreateComplaint(
    google::cloud::paymentgateway::issuerswitch::v1::
        CreateComplaintRequest const&) {
  return google::cloud::make_ready_future<
      StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Complaint>>(
      Status(StatusCode::kUnimplemented, "not implemented"));
}

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Complaint>>
IssuerSwitchResolutionsConnection::ResolveComplaint(
    google::cloud::paymentgateway::issuerswitch::v1::
        ResolveComplaintRequest const&) {
  return google::cloud::make_ready_future<
      StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Complaint>>(
      Status(StatusCode::kUnimplemented, "not implemented"));
}

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Dispute>>
IssuerSwitchResolutionsConnection::CreateDispute(
    google::cloud::paymentgateway::issuerswitch::v1::
        CreateDisputeRequest const&) {
  return google::cloud::make_ready_future<
      StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Dispute>>(
      Status(StatusCode::kUnimplemented, "not implemented"));
}

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Dispute>>
IssuerSwitchResolutionsConnection::ResolveDispute(
    google::cloud::paymentgateway::issuerswitch::v1::
        ResolveDisputeRequest const&) {
  return google::cloud::make_ready_future<
      StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Dispute>>(
      Status(StatusCode::kUnimplemented, "not implemented"));
}

std::shared_ptr<IssuerSwitchResolutionsConnection>
MakeIssuerSwitchResolutionsConnection(Options options) {
  internal::CheckExpectedOptions<CommonOptionList, GrpcOptionList,
                                 UnifiedCredentialsOptionList,
                                 IssuerSwitchResolutionsPolicyOptionList>(
      options, __func__);
  options = paymentgateway_issuerswitch_v1_internal::
      IssuerSwitchResolutionsDefaultOptions(std::move(options));
  auto background = internal::MakeBackgroundThreadsFactory(options)();
  auto stub = paymentgateway_issuerswitch_v1_internal::
      CreateDefaultIssuerSwitchResolutionsStub(background->cq(), options);
  return std::make_shared<paymentgateway_issuerswitch_v1_internal::
                              IssuerSwitchResolutionsConnectionImpl>(
      std::move(background), std::move(stub), std::move(options));
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1
}  // namespace cloud
}  // namespace google
