// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/transactions.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_ISSUER_SWITCH_TRANSACTIONS_CONNECTION_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_ISSUER_SWITCH_TRANSACTIONS_CONNECTION_H

#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_transactions_retry_traits.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_transactions_stub.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_transactions_connection_idempotency_policy.h"
#include "google/cloud/backoff_policy.h"
#include "google/cloud/future.h"
#include "google/cloud/options.h"
#include "google/cloud/polling_policy.h"
#include "google/cloud/status_or.h"
#include "google/cloud/stream_range.h"
#include "google/cloud/version.h"
#include <google/longrunning/operations.grpc.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

using IssuerSwitchTransactionsRetryPolicy =
    ::google::cloud::internal::TraitBasedRetryPolicy<
        paymentgateway_issuerswitch_v1_internal::
            IssuerSwitchTransactionsRetryTraits>;

using IssuerSwitchTransactionsLimitedTimeRetryPolicy =
    ::google::cloud::internal::LimitedTimeRetryPolicy<
        paymentgateway_issuerswitch_v1_internal::
            IssuerSwitchTransactionsRetryTraits>;

using IssuerSwitchTransactionsLimitedErrorCountRetryPolicy =
    ::google::cloud::internal::LimitedErrorCountRetryPolicy<
        paymentgateway_issuerswitch_v1_internal::
            IssuerSwitchTransactionsRetryTraits>;

/**
 * The `IssuerSwitchTransactionsConnection` object for
 * `IssuerSwitchTransactionsClient`.
 *
 * This interface defines virtual methods for each of the user-facing overload
 * sets in `IssuerSwitchTransactionsClient`. This allows users to inject custom
 * behavior (e.g., with a Google Mock object) when writing tests that use
 * objects of type `IssuerSwitchTransactionsClient`.
 *
 * To create a concrete instance, see
 * `MakeIssuerSwitchTransactionsConnection()`.
 *
 * For mocking, see
 * `paymentgateway_issuerswitch_v1_mocks::MockIssuerSwitchTransactionsConnection`.
 */
class IssuerSwitchTransactionsConnection {
 public:
  virtual ~IssuerSwitchTransactionsConnection() = 0;

  virtual Options options() { return Options{}; }

  virtual StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::MetadataTransaction>
  ListMetadataTransactions(google::cloud::paymentgateway::issuerswitch::v1::
                               ListMetadataTransactionsRequest request);

  virtual StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::FinancialTransaction>
  ListFinancialTransactions(google::cloud::paymentgateway::issuerswitch::v1::
                                ListFinancialTransactionsRequest request);

  virtual StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::MandateTransaction>
  ListMandateTransactions(google::cloud::paymentgateway::issuerswitch::v1::
                              ListMandateTransactionsRequest request);

  virtual StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::ComplaintTransaction>
  ListComplaintTransactions(google::cloud::paymentgateway::issuerswitch::v1::
                                ListComplaintTransactionsRequest request);

  virtual future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                              ExportFinancialTransactionsResponse>>
  ExportFinancialTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportFinancialTransactionsRequest const& request);

  virtual future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                              ExportMetadataTransactionsResponse>>
  ExportMetadataTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportMetadataTransactionsRequest const& request);

  virtual future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                              ExportMandateTransactionsResponse>>
  ExportMandateTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportMandateTransactionsRequest const& request);

  virtual future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                              ExportComplaintTransactionsResponse>>
  ExportComplaintTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportComplaintTransactionsRequest const& request);
};

/**
 * A factory function to construct an object of type
 * `IssuerSwitchTransactionsConnection`.
 *
 * The returned connection object should not be used directly; instead it
 * should be passed as an argument to the constructor of
 * IssuerSwitchTransactionsClient.
 *
 * The optional @p options argument may be used to configure aspects of the
 * returned `IssuerSwitchTransactionsConnection`. Expected options are any of
 * the types in the following option lists:
 *
 * - `google::cloud::CommonOptionList`
 * - `google::cloud::GrpcOptionList`
 * - `google::cloud::UnifiedCredentialsOptionList`
 * -
 * `google::cloud::paymentgateway_issuerswitch_v1::IssuerSwitchTransactionsPolicyOptionList`
 *
 * @note Unexpected options will be ignored. To log unexpected options instead,
 *     set `GOOGLE_CLOUD_CPP_ENABLE_CLOG=yes` in the environment.
 *
 * @param options (optional) Configure the `IssuerSwitchTransactionsConnection`
 * created by this function.
 */
std::shared_ptr<IssuerSwitchTransactionsConnection>
MakeIssuerSwitchTransactionsConnection(Options options = {});

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_ISSUER_SWITCH_TRANSACTIONS_CONNECTION_H
