// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/resolutions.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_ISSUER_SWITCH_RESOLUTIONS_CONNECTION_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_ISSUER_SWITCH_RESOLUTIONS_CONNECTION_H

#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_resolutions_retry_traits.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_resolutions_stub.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_resolutions_connection_idempotency_policy.h"
#include "google/cloud/backoff_policy.h"
#include "google/cloud/future.h"
#include "google/cloud/options.h"
#include "google/cloud/polling_policy.h"
#include "google/cloud/status_or.h"
#include "google/cloud/version.h"
#include <google/longrunning/operations.grpc.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

using IssuerSwitchResolutionsRetryPolicy =
    ::google::cloud::internal::TraitBasedRetryPolicy<
        paymentgateway_issuerswitch_v1_internal::
            IssuerSwitchResolutionsRetryTraits>;

using IssuerSwitchResolutionsLimitedTimeRetryPolicy =
    ::google::cloud::internal::LimitedTimeRetryPolicy<
        paymentgateway_issuerswitch_v1_internal::
            IssuerSwitchResolutionsRetryTraits>;

using IssuerSwitchResolutionsLimitedErrorCountRetryPolicy =
    ::google::cloud::internal::LimitedErrorCountRetryPolicy<
        paymentgateway_issuerswitch_v1_internal::
            IssuerSwitchResolutionsRetryTraits>;

/**
 * The `IssuerSwitchResolutionsConnection` object for
 * `IssuerSwitchResolutionsClient`.
 *
 * This interface defines virtual methods for each of the user-facing overload
 * sets in `IssuerSwitchResolutionsClient`. This allows users to inject custom
 * behavior (e.g., with a Google Mock object) when writing tests that use
 * objects of type `IssuerSwitchResolutionsClient`.
 *
 * To create a concrete instance, see `MakeIssuerSwitchResolutionsConnection()`.
 *
 * For mocking, see
 * `paymentgateway_issuerswitch_v1_mocks::MockIssuerSwitchResolutionsConnection`.
 */
class IssuerSwitchResolutionsConnection {
 public:
  virtual ~IssuerSwitchResolutionsConnection() = 0;

  virtual Options options() { return Options{}; }

  virtual future<
      StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Complaint>>
  CreateComplaint(google::cloud::paymentgateway::issuerswitch::v1::
                      CreateComplaintRequest const& request);

  virtual future<
      StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Complaint>>
  ResolveComplaint(google::cloud::paymentgateway::issuerswitch::v1::
                       ResolveComplaintRequest const& request);

  virtual future<
      StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Dispute>>
  CreateDispute(google::cloud::paymentgateway::issuerswitch::v1::
                    CreateDisputeRequest const& request);

  virtual future<
      StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Dispute>>
  ResolveDispute(google::cloud::paymentgateway::issuerswitch::v1::
                     ResolveDisputeRequest const& request);
};

/**
 * A factory function to construct an object of type
 * `IssuerSwitchResolutionsConnection`.
 *
 * The returned connection object should not be used directly; instead it
 * should be passed as an argument to the constructor of
 * IssuerSwitchResolutionsClient.
 *
 * The optional @p options argument may be used to configure aspects of the
 * returned `IssuerSwitchResolutionsConnection`. Expected options are any of the
 * types in the following option lists:
 *
 * - `google::cloud::CommonOptionList`
 * - `google::cloud::GrpcOptionList`
 * - `google::cloud::UnifiedCredentialsOptionList`
 * -
 * `google::cloud::paymentgateway_issuerswitch_v1::IssuerSwitchResolutionsPolicyOptionList`
 *
 * @note Unexpected options will be ignored. To log unexpected options instead,
 *     set `GOOGLE_CLOUD_CPP_ENABLE_CLOG=yes` in the environment.
 *
 * @param options (optional) Configure the `IssuerSwitchResolutionsConnection`
 * created by this function.
 */
std::shared_ptr<IssuerSwitchResolutionsConnection>
MakeIssuerSwitchResolutionsConnection(Options options = {});

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_ISSUER_SWITCH_RESOLUTIONS_CONNECTION_H
