// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/resolutions.proto

#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_resolutions_client.h"
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

IssuerSwitchResolutionsClient::IssuerSwitchResolutionsClient(
    std::shared_ptr<IssuerSwitchResolutionsConnection> connection, Options opts)
    : connection_(std::move(connection)),
      options_(
          internal::MergeOptions(std::move(opts), connection_->options())) {}
IssuerSwitchResolutionsClient::~IssuerSwitchResolutionsClient() = default;

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Complaint>>
IssuerSwitchResolutionsClient::CreateComplaint(
    std::string const& parent,
    google::cloud::paymentgateway::issuerswitch::v1::Complaint const& complaint,
    Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  google::cloud::paymentgateway::issuerswitch::v1::CreateComplaintRequest
      request;
  request.set_parent(parent);
  *request.mutable_complaint() = complaint;
  return connection_->CreateComplaint(request);
}

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Complaint>>
IssuerSwitchResolutionsClient::CreateComplaint(
    google::cloud::paymentgateway::issuerswitch::v1::
        CreateComplaintRequest const& request,
    Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->CreateComplaint(request);
}

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Complaint>>
IssuerSwitchResolutionsClient::ResolveComplaint(
    google::cloud::paymentgateway::issuerswitch::v1::Complaint const& complaint,
    Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  google::cloud::paymentgateway::issuerswitch::v1::ResolveComplaintRequest
      request;
  *request.mutable_complaint() = complaint;
  return connection_->ResolveComplaint(request);
}

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Complaint>>
IssuerSwitchResolutionsClient::ResolveComplaint(
    google::cloud::paymentgateway::issuerswitch::v1::
        ResolveComplaintRequest const& request,
    Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->ResolveComplaint(request);
}

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Dispute>>
IssuerSwitchResolutionsClient::CreateDispute(
    std::string const& parent,
    google::cloud::paymentgateway::issuerswitch::v1::Dispute const& dispute,
    Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  google::cloud::paymentgateway::issuerswitch::v1::CreateDisputeRequest request;
  request.set_parent(parent);
  *request.mutable_dispute() = dispute;
  return connection_->CreateDispute(request);
}

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Dispute>>
IssuerSwitchResolutionsClient::CreateDispute(
    google::cloud::paymentgateway::issuerswitch::v1::CreateDisputeRequest const&
        request,
    Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->CreateDispute(request);
}

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Dispute>>
IssuerSwitchResolutionsClient::ResolveDispute(
    google::cloud::paymentgateway::issuerswitch::v1::Dispute const& dispute,
    Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  google::cloud::paymentgateway::issuerswitch::v1::ResolveDisputeRequest
      request;
  *request.mutable_dispute() = dispute;
  return connection_->ResolveDispute(request);
}

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Dispute>>
IssuerSwitchResolutionsClient::ResolveDispute(
    google::cloud::paymentgateway::issuerswitch::v1::
        ResolveDisputeRequest const& request,
    Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->ResolveDispute(request);
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1
}  // namespace cloud
}  // namespace google
