// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/transactions.proto

#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_transactions_connection_idempotency_policy.h"
#include "absl/memory/memory.h"
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

using ::google::cloud::Idempotency;

IssuerSwitchTransactionsConnectionIdempotencyPolicy::
    ~IssuerSwitchTransactionsConnectionIdempotencyPolicy() = default;

std::unique_ptr<IssuerSwitchTransactionsConnectionIdempotencyPolicy>
IssuerSwitchTransactionsConnectionIdempotencyPolicy::clone() const {
  return absl::make_unique<IssuerSwitchTransactionsConnectionIdempotencyPolicy>(
      *this);
}

Idempotency
IssuerSwitchTransactionsConnectionIdempotencyPolicy::ListMetadataTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ListMetadataTransactionsRequest) {  // NOLINT
  return Idempotency::kIdempotent;
}

Idempotency
IssuerSwitchTransactionsConnectionIdempotencyPolicy::ListFinancialTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ListFinancialTransactionsRequest) {  // NOLINT
  return Idempotency::kIdempotent;
}

Idempotency
IssuerSwitchTransactionsConnectionIdempotencyPolicy::ListMandateTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ListMandateTransactionsRequest) {  // NOLINT
  return Idempotency::kIdempotent;
}

Idempotency
IssuerSwitchTransactionsConnectionIdempotencyPolicy::ListComplaintTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ListComplaintTransactionsRequest) {  // NOLINT
  return Idempotency::kIdempotent;
}

Idempotency IssuerSwitchTransactionsConnectionIdempotencyPolicy::
    ExportFinancialTransactions(
        google::cloud::paymentgateway::issuerswitch::v1::
            ExportFinancialTransactionsRequest const&) {
  return Idempotency::kNonIdempotent;
}

Idempotency
IssuerSwitchTransactionsConnectionIdempotencyPolicy::ExportMetadataTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ExportMetadataTransactionsRequest const&) {
  return Idempotency::kNonIdempotent;
}

Idempotency
IssuerSwitchTransactionsConnectionIdempotencyPolicy::ExportMandateTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ExportMandateTransactionsRequest const&) {
  return Idempotency::kNonIdempotent;
}

Idempotency IssuerSwitchTransactionsConnectionIdempotencyPolicy::
    ExportComplaintTransactions(
        google::cloud::paymentgateway::issuerswitch::v1::
            ExportComplaintTransactionsRequest const&) {
  return Idempotency::kNonIdempotent;
}

std::unique_ptr<IssuerSwitchTransactionsConnectionIdempotencyPolicy>
MakeDefaultIssuerSwitchTransactionsConnectionIdempotencyPolicy() {
  return absl::make_unique<
      IssuerSwitchTransactionsConnectionIdempotencyPolicy>();
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1
}  // namespace cloud
}  // namespace google
