// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/transactions.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_ISSUER_SWITCH_TRANSACTIONS_CLIENT_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_ISSUER_SWITCH_TRANSACTIONS_CLIENT_H

#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_transactions_connection.h"
#include "google/cloud/future.h"
#include "google/cloud/options.h"
#include "google/cloud/polling_policy.h"
#include "google/cloud/status_or.h"
#include "google/cloud/version.h"
#include <google/longrunning/operations.grpc.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

///
/// Lists and exports transactions processed by the issuer switch.
///
/// @par Equality
///
/// Instances of this class created via copy-construction or copy-assignment
/// always compare equal. Instances created with equal
/// `std::shared_ptr<*Connection>` objects compare equal. Objects that compare
/// equal share the same underlying resources.
///
/// @par Performance
///
/// Creating a new instance of this class is a relatively expensive operation,
/// new objects establish new connections to the service. In contrast,
/// copy-construction, move-construction, and the corresponding assignment
/// operations are relatively efficient as the copies share all underlying
/// resources.
///
/// @par Thread Safety
///
/// Concurrent access to different instances of this class, even if they compare
/// equal, is guaranteed to work. Two or more threads operating on the same
/// instance of this class is not guaranteed to work. Since copy-construction
/// and move-construction is a relatively efficient operation, consider using
/// such a copy when using this class from multiple threads.
///
class IssuerSwitchTransactionsClient {
 public:
  explicit IssuerSwitchTransactionsClient(
      std::shared_ptr<IssuerSwitchTransactionsConnection> connection,
      Options opts = {});
  ~IssuerSwitchTransactionsClient();

  ///@{
  // @name Copy and move support
  IssuerSwitchTransactionsClient(IssuerSwitchTransactionsClient const&) =
      default;
  IssuerSwitchTransactionsClient& operator=(
      IssuerSwitchTransactionsClient const&) = default;
  IssuerSwitchTransactionsClient(IssuerSwitchTransactionsClient&&) = default;
  IssuerSwitchTransactionsClient& operator=(IssuerSwitchTransactionsClient&&) =
      default;
  ///@}

  ///@{
  // @name Equality
  friend bool operator==(IssuerSwitchTransactionsClient const& a,
                         IssuerSwitchTransactionsClient const& b) {
    return a.connection_ == b.connection_;
  }
  friend bool operator!=(IssuerSwitchTransactionsClient const& a,
                         IssuerSwitchTransactionsClient const& b) {
    return !(a == b);
  }
  ///@}

  ///
  /// List metadata transactions that satisfy the specified filter criteria.
  ///
  /// @param parent  Required. The parent resource. The format is
  /// `projects/{project}`.
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::MetadataTransaction,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L392}
  ///
  /// [google.cloud.paymentgateway.issuerswitch.v1.ListMetadataTransactionsRequest]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L612}
  /// [google.cloud.paymentgateway.issuerswitch.v1.MetadataTransaction]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L392}
  ///
  StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::MetadataTransaction>
  ListMetadataTransactions(std::string const& parent, Options opts = {});

  ///
  /// List metadata transactions that satisfy the specified filter criteria.
  ///
  /// @param request
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::ListMetadataTransactionsRequest,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L612}
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::MetadataTransaction,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L392}
  ///
  /// [google.cloud.paymentgateway.issuerswitch.v1.ListMetadataTransactionsRequest]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L612}
  /// [google.cloud.paymentgateway.issuerswitch.v1.MetadataTransaction]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L392}
  ///
  StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::MetadataTransaction>
  ListMetadataTransactions(google::cloud::paymentgateway::issuerswitch::v1::
                               ListMetadataTransactionsRequest request,
                           Options opts = {});

  ///
  /// List financial transactions that satisfy specified filter criteria.
  ///
  /// @param parent  Required. The parent resource. The format is
  /// `projects/{project}`.
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::FinancialTransaction,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L412}
  ///
  /// [google.cloud.paymentgateway.issuerswitch.v1.ListFinancialTransactionsRequest]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L686}
  /// [google.cloud.paymentgateway.issuerswitch.v1.FinancialTransaction]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L412}
  ///
  StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::FinancialTransaction>
  ListFinancialTransactions(std::string const& parent, Options opts = {});

  ///
  /// List financial transactions that satisfy specified filter criteria.
  ///
  /// @param request
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::ListFinancialTransactionsRequest,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L686}
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::FinancialTransaction,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L412}
  ///
  /// [google.cloud.paymentgateway.issuerswitch.v1.ListFinancialTransactionsRequest]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L686}
  /// [google.cloud.paymentgateway.issuerswitch.v1.FinancialTransaction]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L412}
  ///
  StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::FinancialTransaction>
  ListFinancialTransactions(google::cloud::paymentgateway::issuerswitch::v1::
                                ListFinancialTransactionsRequest request,
                            Options opts = {});

  ///
  /// List mandate transactions that satisfy specified filter criteria.
  ///
  /// @param parent  Required. The parent resource. The format is
  /// `projects/{project}`.
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::MandateTransaction,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L443}
  ///
  /// [google.cloud.paymentgateway.issuerswitch.v1.ListMandateTransactionsRequest]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L774}
  /// [google.cloud.paymentgateway.issuerswitch.v1.MandateTransaction]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L443}
  ///
  StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::MandateTransaction>
  ListMandateTransactions(std::string const& parent, Options opts = {});

  ///
  /// List mandate transactions that satisfy specified filter criteria.
  ///
  /// @param request
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::ListMandateTransactionsRequest,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L774}
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::MandateTransaction,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L443}
  ///
  /// [google.cloud.paymentgateway.issuerswitch.v1.ListMandateTransactionsRequest]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L774}
  /// [google.cloud.paymentgateway.issuerswitch.v1.MandateTransaction]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L443}
  ///
  StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::MandateTransaction>
  ListMandateTransactions(google::cloud::paymentgateway::issuerswitch::v1::
                              ListMandateTransactionsRequest request,
                          Options opts = {});

  ///
  /// List complaint transactions that satisfy specified filter criteria.
  ///
  /// @param parent  Required. The parent resource. The format is
  /// `projects/{project}`.
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::ComplaintTransaction,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L584}
  ///
  /// [google.cloud.paymentgateway.issuerswitch.v1.ListComplaintTransactionsRequest]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L872}
  /// [google.cloud.paymentgateway.issuerswitch.v1.ComplaintTransaction]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L584}
  ///
  StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::ComplaintTransaction>
  ListComplaintTransactions(std::string const& parent, Options opts = {});

  ///
  /// List complaint transactions that satisfy specified filter criteria.
  ///
  /// @param request
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::ListComplaintTransactionsRequest,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L872}
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::ComplaintTransaction,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L584}
  ///
  /// [google.cloud.paymentgateway.issuerswitch.v1.ListComplaintTransactionsRequest]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L872}
  /// [google.cloud.paymentgateway.issuerswitch.v1.ComplaintTransaction]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L584}
  ///
  StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::ComplaintTransaction>
  ListComplaintTransactions(google::cloud::paymentgateway::issuerswitch::v1::
                                ListComplaintTransactionsRequest request,
                            Options opts = {});

  ///
  /// Export financial transactions received within the specified time range as
  /// a file into a configured target location. The returned `Operation` type
  /// has the following method-specific fields:
  ///
  /// - `metadata`:
  /// [ExportFinancialTransactionsMetadata][google.cloud.paymentgateway.issuerswitch.v1.ExportFinancialTransactionsMetadata]
  /// - `response`:
  /// [ExportFinancialTransactionsResponse][google.cloud.paymentgateway.issuerswitch.v1.ExportFinancialTransactionsResponse]
  ///
  /// The exported file will be in the standard CSV format where each row in the
  /// file represents a transaction. The file has the following fields in order:
  ///
  /// - `TransactionID` - UPI transaction ID.
  /// - `TransactionType` - Type of the transaction. This will be one of
  /// `TRANSACTION_TYPE_CREDIT`, `TRANSACTION_TYPE_DEBIT` or
  /// `TRANSACTION_TYPE_REVERSAL`.
  /// - `TransactionSubType` - Subtype of the transaction. This will be one
  /// of `COLLECT`, `DEBIT` or `PAY`.
  /// - `RequestReceivedTimestamp` - Timestamp (in UTC) indicating when the
  /// transaction API request was received by the issuer switch.
  /// - `CreationTime` - Timestamp (in UTC) indicating when the
  /// issuer switch created the transaction resource for processing the
  /// transaction.
  /// - `State` - State of the transaction. This will be one of `FAILED` or
  /// `SUCCEEDED`.
  /// - `RRN` - Retrieval reference number associated with the transaction.
  /// - `PayerVPA` - Virtual Payment Address (VPA) of the payer.
  /// - `PayerMobileNumber` - Mobile number of the payer.
  /// - `PayerIFSCCode` - IFSC code of the payer's bank account.
  /// - `PayerAccountNumber` - Payer's bank account number.
  /// - `PayerAccountType` - Payer's bank account type.
  /// - `PayeeVPA` - Virtual Payment Address (VPA) of the payee.
  /// - `PayeeMobileNumber` - Payee's mobile number.
  /// - `PayeeIFSCCode` - IFSC code of the payee's bank account.
  /// - `PayeeAccountNumber` - Payee's bank account number.
  /// - `PayeeAccountType` - Payee's bank account type.
  /// - `PayeeMerchantID` - Payee's merchant ID, only if the payee is a
  /// merchant.
  /// - `PayeeMerchantName` - Payee's merchant name, only if the payee is a
  /// merchant.
  /// - `PayeeMCC` - Payee's Merchant Category Code (MCC), only if the payee is
  /// a merchant.
  /// - `Currency` - Currency of the amount involved in the transaction.
  /// - `Amount` - Amount involved in the transaction.
  /// - `BankAdapterRequestIDs` - List of Request IDs (colon separated) used
  /// when invoking the Bank Adapter APIs for fulfilling a transaction request.
  /// - `ErrorCode` - Error code of the failed transaction.
  /// - `ErrorMessage` - Error description for the failed transaction.
  /// - `UPIErrorCode` - Error code as per the UPI specification. The issuer
  /// switch maps the ErrorCode to an appropriate error code that complies with
  /// the UPI specification.
  ///
  /// @param request
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::ExportFinancialTransactionsRequest,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L989}
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::ExportFinancialTransactionsResponse,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L1092}
  ///
  /// [google.cloud.paymentgateway.issuerswitch.v1.ExportFinancialTransactionsRequest]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L989}
  /// [google.cloud.paymentgateway.issuerswitch.v1.ExportFinancialTransactionsResponse]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L1092}
  ///
  future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                      ExportFinancialTransactionsResponse>>
  ExportFinancialTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportFinancialTransactionsRequest const& request,
      Options opts = {});

  ///
  /// Export metadata transactions received within the specified time range as a
  /// file into a configured target location. The returned `Operation` type has
  /// the following method-specific fields:
  ///
  /// - `metadata`:
  /// [ExportMetadataTransactionsMetadata][google.cloud.paymentgateway.issuerswitch.v1.ExportMetadataTransactionsMetadata]
  /// - `response`:
  /// [ExportMetadataTransactionsResponse][google.cloud.paymentgateway.issuerswitch.v1.ExportMetadataTransactionsResponse]
  ///
  /// The exported file will be in the standard CSV format where each row in the
  /// file represents a transaction. The file has the following fields in order:
  ///
  /// - `TransactionID` - UPI transaction ID.
  /// - `APIType` - The transaction's API type. The value will be of the
  /// [ApiType][google.cloud.paymentgateway.issuerswitch.v1.ApiType] enum.
  /// - `TransactionType` - Type of the transaction. The value will be of the
  /// [TransactionType][google.cloud.paymentgateway.issuerswitch.v1.TransactionType]
  /// enum.
  /// - `RequestReceivedTimestamp` - Timestamp (in UTC) indicating when the
  /// transaction's API request was received by the issuer switch.
  /// - `CreationTime` - Timestamp (in UTC) indicating when the
  /// issuer switch created the transaction resource for processing the
  /// transaction.
  /// - `State` - State of transaction. This will be one of `FAILED` or
  /// `SUCCEEDED`.
  /// - `OriginVPA` - Virtual Payment Address (VPA) of the originator of the
  /// transaction.
  /// - `BankAdapterRequestIDs` - List of Request IDs (colon separated) used
  /// when invoking the Bank Adapter APIs for fulfilling a transaction request.
  /// - `ErrorCode` - Error code of the failed transaction.
  /// - `ErrorMessage` - Error description for the failed transaction.
  /// - `UPIErrorCode` - Error code as per the UPI specification. The issuer
  /// switch maps the ErrorCode to an appropriate error code that complies with
  /// the UPI specification.
  ///
  /// @param request
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::ExportMetadataTransactionsRequest,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L1013}
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::ExportMetadataTransactionsResponse,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L1098}
  ///
  /// [google.cloud.paymentgateway.issuerswitch.v1.ExportMetadataTransactionsRequest]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L1013}
  /// [google.cloud.paymentgateway.issuerswitch.v1.ExportMetadataTransactionsResponse]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L1098}
  ///
  future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                      ExportMetadataTransactionsResponse>>
  ExportMetadataTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportMetadataTransactionsRequest const& request,
      Options opts = {});

  ///
  /// Export mandate transactions received within the specified time range as a
  /// file into a configured target location. The returned `Operation` type has
  /// the following method-specific fields:
  ///
  /// - `metadata`:
  /// [ExportMandateTransactionsMetadata][google.cloud.paymentgateway.issuerswitch.v1.ExportMandateTransactionsMetadata]
  /// - `response`:
  /// [ExportMandateTransactionsResponse][google.cloud.paymentgateway.issuerswitch.v1.ExportMandateTransactionsResponse]
  ///
  /// The exported file will be in the standard CSV format where each row in the
  /// file represents a transaction. The file has the following fields in order:
  ///
  /// - `TransactionID` - UPI transaction ID.
  /// - `UniqueMandateNumber` - UPI Unique Mandate Number.
  /// - `TransactionType` - Type of the transaction. This will be one of
  /// `TRANSACTION_TYPE_CREATE`, `TRANSACTION_TYPE_REVOKE` or
  /// `TRANSACTION_TYPE_UPDATE`.
  /// - `RequestReceivedTimestamp` - Timestamp (in UTC) indicating when the
  /// mandate API request was received by the issuer switch.
  /// - `CreationTime` - Timestamp (in UTC) indicating when the
  /// issuer switch created the transaction resource for processing the
  /// transaction.
  /// - `State` - State of the transaction. This will be one of
  /// `FAILED` or `SUCCEEDED`.
  /// - `PayerVPA` - Virtual Payment Address (VPA) of the payer.
  /// - `PayerMobileNumber` - Mobile number of the payer.
  /// - `PayeeVPA` - Virtual Payment Address (VPA) of the payee.
  /// - `PayeeMobileNumber` - Mobile number of the payee.
  /// - `PayeeMerchantID` - Payee's merchant ID.
  /// - `Amount` - Amount specified in the mandate.
  /// - `RecurrencePattern` - Reccurence pattern of the mandate. The value will
  /// be of the [MandateTransaction.RecurrencePattern][] enum.
  /// - `RecurrenceRuleType` - Reccurrence rule type of the mandate. The value
  /// will be of the
  /// [MandateTransaction.RecurrenceRuleType][google.cloud.paymentgateway.issuerswitch.v1.MandateTransaction.RecurrenceRuleType]
  /// enum.
  /// - `RecurrenceRuleValue` - Recurrence rule value of the mandate.
  /// - `Revokeable` - Boolean value specifying if the mandate is revokable.
  /// - `StartDate` - The start date of the mandate in `YYYY-MM-DD` format.
  /// - `EndDate` - The end date of the mandate in `YYYY-MM-DD` format.
  /// - `AmountRuleType` - The amount rule of the mandate. The value will
  /// be of the
  /// [MandateTransaction.AmountRuleType][google.cloud.paymentgateway.issuerswitch.v1.MandateTransaction.AmountRuleType]
  /// enum.
  /// - `ApprovalReference` - The block funds reference generated by the bank,
  /// if funds have been blocked for the mandate. This column have a value only
  /// when the RecurrencePattern is ONETIME.
  /// - `BlockFunds` - Boolean value specifying if the mandate transaction
  /// requested to block funds.
  /// - `LastUpdateTime` - Timestamp (in UTC) indicating when was the last
  /// modification made to the mandate.
  /// - `BankAdapterRequestIDs` - List of Request IDs (colon separated) used
  /// when invoking the Bank Adapter APIs for fulfilling a transaction request.
  /// - `ErrorCode` - Error code of the failed transaction.
  /// - `ErrorMessage` - Error description for the failed transaction.
  /// - `UPIErrorCode` - Error code as per the UPI specification. The issuer
  /// switch maps the ErrorCode to an appropriate error code that complies with
  /// the UPI specification.
  ///
  /// @param request
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::ExportMandateTransactionsRequest,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L1041}
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::ExportMandateTransactionsResponse,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L1104}
  ///
  /// [google.cloud.paymentgateway.issuerswitch.v1.ExportMandateTransactionsRequest]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L1041}
  /// [google.cloud.paymentgateway.issuerswitch.v1.ExportMandateTransactionsResponse]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L1104}
  ///
  future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                      ExportMandateTransactionsResponse>>
  ExportMandateTransactions(google::cloud::paymentgateway::issuerswitch::v1::
                                ExportMandateTransactionsRequest const& request,
                            Options opts = {});

  ///
  /// Export complaint transactions received within the specified time range as
  /// a file into a configured target location. The returned `Operation` type
  /// has the following method-specific fields:
  ///
  /// - `metadata`:
  /// [ExportComplaintTransactionsMetadata][google.cloud.paymentgateway.issuerswitch.v1.ExportComplaintTransactionsMetadata]
  /// - `response`:
  /// [ExportComplaintTransactionsResponse][google.cloud.paymentgateway.issuerswitch.v1.ExportComplaintTransactionsResponse]
  ///
  /// The exported file will be in the standard CSV format where each row in the
  /// file represents a transaction. The file has the following fields in order:
  ///
  /// - `TransactionID` - UPI transaction ID.
  /// - `TransactionType` - Type of the transaction. This will be one of
  /// `TRANSACTION_TYPE_CHECK_STATUS`, `TRANSACTION_TYPE_COMPLAINT`,
  /// `TRANSACTION_TYPE_REVERSAL`, `TRANSACTION_TYPE_DISPUTE`,
  /// `TRANSACTION_TYPE_REFUND` or `TRANSACTION_TYPE_STATUS_UPDATE`.
  /// - `CreationTime` - Timestamp (in UTC) indicating when the issuer switch
  /// created the transaction resource for processing the transaction.
  /// - `State` - State of the transaction. This will be one of
  /// `FAILED` or `SUCCEEDED`.
  /// - `OriginalRRN` - RRN of the original payment transaction.
  /// - `BankType` - The subtype of the transaction based on the bank involved.
  /// - `OriginalTransactionID` - Transaction ID of the original unresolved
  /// transaction.
  /// - `RaiseComplaintAdjFlag` - Indicates the type of action to raise the
  /// complaint.
  /// - `RaiseComplaintAdjCode` - Indicates the reason of action to raise the
  /// complaint.
  /// - `ResolveComplaintAdjFlag` - Indicates the type of action to resolve the
  /// complaint.
  /// - `ResolveComplaintAdjCode` - Indicates the reason of action to resolve
  /// the complaint.
  /// - `RaiseDisputeAdjFlag` - Indicates the type of action to raise the
  /// dispute.
  /// - `RaiseDisputeAdjCode` - Indicates the reason of action to raise the
  /// dispute.
  /// - `ResolveDisputeAdjFlag` - Indicates the type of action to resolve the
  /// dispute.
  /// - `ResolveDisputeAdjCode` - Indicates the reason of action to resolve the
  /// dispute.
  /// - `Amount` - Amount to be resolved.
  /// - `CurrentCycle` - Boolean value specifying if the complaint / dispute
  /// belongs to current settlement cycle or not.
  /// - `CRN` - Defines the Complaint Reference number.
  /// - `AdjTime` - Indicates the time when the resolution was done.
  /// - `RespAdjFlag` - Indicates the response category type.
  /// - `RespAdjCode` - Indicates the response reason used.
  /// - `AdjRemarks` - Indicates the additional remarks for the complaint /
  /// dispute.
  /// - `BankAdapterRequestIDs` - List of Request IDs (colon separated) used
  /// when invoking the Bank Adapter APIs for fulfilling a transaction request.
  /// - `ErrorCode` - Error code of the failed transaction.
  /// - `ErrorMessage` - Error description for the failed transaction.
  /// - `UPIErrorCode` - Error code as per the UPI specification. The issuer
  /// switch service maps the ErrorCode to an appropriate error code that
  /// complies with the UPI specification.
  ///
  /// @param request
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::ExportComplaintTransactionsRequest,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L1065}
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return
  /// @googleapis_link{google::cloud::paymentgateway::issuerswitch::v1::ExportComplaintTransactionsResponse,google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L1110}
  ///
  /// [google.cloud.paymentgateway.issuerswitch.v1.ExportComplaintTransactionsRequest]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L1065}
  /// [google.cloud.paymentgateway.issuerswitch.v1.ExportComplaintTransactionsResponse]:
  /// @googleapis_reference_link{google/cloud/paymentgateway/issuerswitch/v1/transactions.proto#L1110}
  ///
  future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                      ExportComplaintTransactionsResponse>>
  ExportComplaintTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportComplaintTransactionsRequest const& request,
      Options opts = {});

 private:
  std::shared_ptr<IssuerSwitchTransactionsConnection> connection_;
  Options options_;
};

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_ISSUER_SWITCH_TRANSACTIONS_CLIENT_H
