// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/transactions.proto

#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_transactions_client.h"
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

IssuerSwitchTransactionsClient::IssuerSwitchTransactionsClient(
    std::shared_ptr<IssuerSwitchTransactionsConnection> connection,
    Options opts)
    : connection_(std::move(connection)),
      options_(
          internal::MergeOptions(std::move(opts), connection_->options())) {}
IssuerSwitchTransactionsClient::~IssuerSwitchTransactionsClient() = default;

StreamRange<
    google::cloud::paymentgateway::issuerswitch::v1::MetadataTransaction>
IssuerSwitchTransactionsClient::ListMetadataTransactions(
    std::string const& parent, Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  google::cloud::paymentgateway::issuerswitch::v1::
      ListMetadataTransactionsRequest request;
  request.set_parent(parent);
  return connection_->ListMetadataTransactions(request);
}

StreamRange<
    google::cloud::paymentgateway::issuerswitch::v1::MetadataTransaction>
IssuerSwitchTransactionsClient::ListMetadataTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ListMetadataTransactionsRequest request,
    Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->ListMetadataTransactions(std::move(request));
}

StreamRange<
    google::cloud::paymentgateway::issuerswitch::v1::FinancialTransaction>
IssuerSwitchTransactionsClient::ListFinancialTransactions(
    std::string const& parent, Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  google::cloud::paymentgateway::issuerswitch::v1::
      ListFinancialTransactionsRequest request;
  request.set_parent(parent);
  return connection_->ListFinancialTransactions(request);
}

StreamRange<
    google::cloud::paymentgateway::issuerswitch::v1::FinancialTransaction>
IssuerSwitchTransactionsClient::ListFinancialTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ListFinancialTransactionsRequest request,
    Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->ListFinancialTransactions(std::move(request));
}

StreamRange<google::cloud::paymentgateway::issuerswitch::v1::MandateTransaction>
IssuerSwitchTransactionsClient::ListMandateTransactions(
    std::string const& parent, Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  google::cloud::paymentgateway::issuerswitch::v1::
      ListMandateTransactionsRequest request;
  request.set_parent(parent);
  return connection_->ListMandateTransactions(request);
}

StreamRange<google::cloud::paymentgateway::issuerswitch::v1::MandateTransaction>
IssuerSwitchTransactionsClient::ListMandateTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ListMandateTransactionsRequest request,
    Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->ListMandateTransactions(std::move(request));
}

StreamRange<
    google::cloud::paymentgateway::issuerswitch::v1::ComplaintTransaction>
IssuerSwitchTransactionsClient::ListComplaintTransactions(
    std::string const& parent, Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  google::cloud::paymentgateway::issuerswitch::v1::
      ListComplaintTransactionsRequest request;
  request.set_parent(parent);
  return connection_->ListComplaintTransactions(request);
}

StreamRange<
    google::cloud::paymentgateway::issuerswitch::v1::ComplaintTransaction>
IssuerSwitchTransactionsClient::ListComplaintTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ListComplaintTransactionsRequest request,
    Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->ListComplaintTransactions(std::move(request));
}

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                    ExportFinancialTransactionsResponse>>
IssuerSwitchTransactionsClient::ExportFinancialTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ExportFinancialTransactionsRequest const& request,
    Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->ExportFinancialTransactions(request);
}

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                    ExportMetadataTransactionsResponse>>
IssuerSwitchTransactionsClient::ExportMetadataTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ExportMetadataTransactionsRequest const& request,
    Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->ExportMetadataTransactions(request);
}

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                    ExportMandateTransactionsResponse>>
IssuerSwitchTransactionsClient::ExportMandateTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ExportMandateTransactionsRequest const& request,
    Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->ExportMandateTransactions(request);
}

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                    ExportComplaintTransactionsResponse>>
IssuerSwitchTransactionsClient::ExportComplaintTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ExportComplaintTransactionsRequest const& request,
    Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->ExportComplaintTransactions(request);
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1
}  // namespace cloud
}  // namespace google
