// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/resolutions.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_ISSUER_SWITCH_RESOLUTIONS_CONNECTION_IDEMPOTENCY_POLICY_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_ISSUER_SWITCH_RESOLUTIONS_CONNECTION_IDEMPOTENCY_POLICY_H

#include "google/cloud/idempotency.h"
#include "google/cloud/internal/retry_policy.h"
#include "google/cloud/version.h"
#include <google/cloud/paymentgateway/issuerswitch/v1/resolutions.grpc.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

class IssuerSwitchResolutionsConnectionIdempotencyPolicy {
 public:
  virtual ~IssuerSwitchResolutionsConnectionIdempotencyPolicy();

  /// Create a new copy of this object.
  virtual std::unique_ptr<IssuerSwitchResolutionsConnectionIdempotencyPolicy>
  clone() const;

  virtual google::cloud::Idempotency CreateComplaint(
      google::cloud::paymentgateway::issuerswitch::v1::
          CreateComplaintRequest const& request);

  virtual google::cloud::Idempotency ResolveComplaint(
      google::cloud::paymentgateway::issuerswitch::v1::
          ResolveComplaintRequest const& request);

  virtual google::cloud::Idempotency CreateDispute(
      google::cloud::paymentgateway::issuerswitch::v1::
          CreateDisputeRequest const& request);

  virtual google::cloud::Idempotency ResolveDispute(
      google::cloud::paymentgateway::issuerswitch::v1::
          ResolveDisputeRequest const& request);
};

std::unique_ptr<IssuerSwitchResolutionsConnectionIdempotencyPolicy>
MakeDefaultIssuerSwitchResolutionsConnectionIdempotencyPolicy();

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_ISSUER_SWITCH_RESOLUTIONS_CONNECTION_IDEMPOTENCY_POLICY_H
