// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/resolutions.proto

#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_resolutions_connection_idempotency_policy.h"
#include "absl/memory/memory.h"
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

using ::google::cloud::Idempotency;

IssuerSwitchResolutionsConnectionIdempotencyPolicy::
    ~IssuerSwitchResolutionsConnectionIdempotencyPolicy() = default;

std::unique_ptr<IssuerSwitchResolutionsConnectionIdempotencyPolicy>
IssuerSwitchResolutionsConnectionIdempotencyPolicy::clone() const {
  return absl::make_unique<IssuerSwitchResolutionsConnectionIdempotencyPolicy>(
      *this);
}

Idempotency IssuerSwitchResolutionsConnectionIdempotencyPolicy::CreateComplaint(
    google::cloud::paymentgateway::issuerswitch::v1::
        CreateComplaintRequest const&) {
  return Idempotency::kNonIdempotent;
}

Idempotency
IssuerSwitchResolutionsConnectionIdempotencyPolicy::ResolveComplaint(
    google::cloud::paymentgateway::issuerswitch::v1::
        ResolveComplaintRequest const&) {
  return Idempotency::kNonIdempotent;
}

Idempotency IssuerSwitchResolutionsConnectionIdempotencyPolicy::CreateDispute(
    google::cloud::paymentgateway::issuerswitch::v1::
        CreateDisputeRequest const&) {
  return Idempotency::kNonIdempotent;
}

Idempotency IssuerSwitchResolutionsConnectionIdempotencyPolicy::ResolveDispute(
    google::cloud::paymentgateway::issuerswitch::v1::
        ResolveDisputeRequest const&) {
  return Idempotency::kNonIdempotent;
}

std::unique_ptr<IssuerSwitchResolutionsConnectionIdempotencyPolicy>
MakeDefaultIssuerSwitchResolutionsConnectionIdempotencyPolicy() {
  return absl::make_unique<
      IssuerSwitchResolutionsConnectionIdempotencyPolicy>();
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1
}  // namespace cloud
}  // namespace google
