// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/transactions.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_ISSUER_SWITCH_TRANSACTIONS_CONNECTION_IDEMPOTENCY_POLICY_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_ISSUER_SWITCH_TRANSACTIONS_CONNECTION_IDEMPOTENCY_POLICY_H

#include "google/cloud/idempotency.h"
#include "google/cloud/internal/retry_policy.h"
#include "google/cloud/version.h"
#include <google/cloud/paymentgateway/issuerswitch/v1/transactions.grpc.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

class IssuerSwitchTransactionsConnectionIdempotencyPolicy {
 public:
  virtual ~IssuerSwitchTransactionsConnectionIdempotencyPolicy();

  /// Create a new copy of this object.
  virtual std::unique_ptr<IssuerSwitchTransactionsConnectionIdempotencyPolicy>
  clone() const;

  virtual google::cloud::Idempotency ListMetadataTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ListMetadataTransactionsRequest request);

  virtual google::cloud::Idempotency ListFinancialTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ListFinancialTransactionsRequest request);

  virtual google::cloud::Idempotency ListMandateTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ListMandateTransactionsRequest request);

  virtual google::cloud::Idempotency ListComplaintTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ListComplaintTransactionsRequest request);

  virtual google::cloud::Idempotency ExportFinancialTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportFinancialTransactionsRequest const& request);

  virtual google::cloud::Idempotency ExportMetadataTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportMetadataTransactionsRequest const& request);

  virtual google::cloud::Idempotency ExportMandateTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportMandateTransactionsRequest const& request);

  virtual google::cloud::Idempotency ExportComplaintTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportComplaintTransactionsRequest const& request);
};

std::unique_ptr<IssuerSwitchTransactionsConnectionIdempotencyPolicy>
MakeDefaultIssuerSwitchTransactionsConnectionIdempotencyPolicy();

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_ISSUER_SWITCH_TRANSACTIONS_CONNECTION_IDEMPOTENCY_POLICY_H
