// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/bigtable/v2/bigtable.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGTABLE_INTERNAL_BIGTABLE_CONNECTION_IMPL_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGTABLE_INTERNAL_BIGTABLE_CONNECTION_IMPL_H

#include "google/cloud/bigtable/bigtable_connection.h"
#include "google/cloud/bigtable/bigtable_connection_idempotency_policy.h"
#include "google/cloud/bigtable/bigtable_options.h"
#include "google/cloud/bigtable/internal/bigtable_retry_traits.h"
#include "google/cloud/bigtable/internal/bigtable_stub.h"
#include "google/cloud/background_threads.h"
#include "google/cloud/backoff_policy.h"
#include "google/cloud/options.h"
#include "google/cloud/status_or.h"
#include "google/cloud/version.h"
#include <memory>

namespace google {
namespace cloud {
namespace bigtable_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

class BigtableConnectionImpl : public bigtable::BigtableConnection {
 public:
  ~BigtableConnectionImpl() override = default;

  BigtableConnectionImpl(
      std::unique_ptr<google::cloud::BackgroundThreads> background,
      std::shared_ptr<bigtable_internal::BigtableStub> stub, Options options);

  Options options() override { return options_; }

  StatusOr<google::bigtable::v2::CheckAndMutateRowResponse> CheckAndMutateRow(
      google::bigtable::v2::CheckAndMutateRowRequest const& request) override;

 private:
  std::unique_ptr<bigtable::BigtableRetryPolicy> retry_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<bigtable::BigtableRetryPolicyOption>()) {
      return options.get<bigtable::BigtableRetryPolicyOption>()->clone();
    }
    return options_.get<bigtable::BigtableRetryPolicyOption>()->clone();
  }

  std::unique_ptr<BackoffPolicy> backoff_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<bigtable::BigtableBackoffPolicyOption>()) {
      return options.get<bigtable::BigtableBackoffPolicyOption>()->clone();
    }
    return options_.get<bigtable::BigtableBackoffPolicyOption>()->clone();
  }

  std::unique_ptr<bigtable::BigtableConnectionIdempotencyPolicy>
  idempotency_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<bigtable::BigtableConnectionIdempotencyPolicyOption>()) {
      return options.get<bigtable::BigtableConnectionIdempotencyPolicyOption>()
          ->clone();
    }
    return options_.get<bigtable::BigtableConnectionIdempotencyPolicyOption>()
        ->clone();
  }

  std::unique_ptr<google::cloud::BackgroundThreads> background_;
  std::shared_ptr<bigtable_internal::BigtableStub> stub_;
  Options options_;
};

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigtable_internal
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGTABLE_INTERNAL_BIGTABLE_CONNECTION_IMPL_H
