// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/bigtable/v2/bigtable.proto

#include "google/cloud/bigtable/internal/bigtable_connection_impl.h"
#include "google/cloud/bigtable/internal/bigtable_option_defaults.h"
#include "google/cloud/background_threads.h"
#include "google/cloud/common_options.h"
#include "google/cloud/grpc_options.h"
#include "google/cloud/internal/resumable_streaming_read_rpc.h"
#include "google/cloud/internal/retry_loop.h"
#include "google/cloud/internal/streaming_read_rpc_logging.h"
#include <memory>

namespace google {
namespace cloud {
namespace bigtable_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

BigtableConnectionImpl::BigtableConnectionImpl(
    std::unique_ptr<google::cloud::BackgroundThreads> background,
    std::shared_ptr<bigtable_internal::BigtableStub> stub, Options options)
    : background_(std::move(background)),
      stub_(std::move(stub)),
      options_(internal::MergeOptions(std::move(options),
                                      bigtable_internal::BigtableDefaultOptions(
                                          BigtableConnection::options()))) {}

StreamRange<google::bigtable::v2::SampleRowKeysResponse>
BigtableConnectionImpl::SampleRowKeys(
    google::bigtable::v2::SampleRowKeysRequest const& request) {
  auto stub = stub_;
  auto retry =
      std::shared_ptr<bigtable::BigtableRetryPolicy const>(retry_policy());
  auto backoff = std::shared_ptr<BackoffPolicy const>(backoff_policy());

  auto factory =
      [stub](google::bigtable::v2::SampleRowKeysRequest const& request) {
        return stub->SampleRowKeys(absl::make_unique<grpc::ClientContext>(),
                                   request);
      };
  auto resumable = internal::MakeResumableStreamingReadRpc<
      google::bigtable::v2::SampleRowKeysResponse,
      google::bigtable::v2::SampleRowKeysRequest>(
      retry->clone(), backoff->clone(), [](std::chrono::milliseconds) {},
      factory, BigtableSampleRowKeysStreamingUpdater, request);
  return internal::MakeStreamRange(
      internal::StreamReader<google::bigtable::v2::SampleRowKeysResponse>(
          [resumable] { return resumable->Read(); }));
}
StatusOr<google::bigtable::v2::CheckAndMutateRowResponse>
BigtableConnectionImpl::CheckAndMutateRow(
    google::bigtable::v2::CheckAndMutateRowRequest const& request) {
  return google::cloud::internal::RetryLoop(
      retry_policy(), backoff_policy(),
      idempotency_policy()->CheckAndMutateRow(request),
      [this](grpc::ClientContext& context,
             google::bigtable::v2::CheckAndMutateRowRequest const& request) {
        return stub_->CheckAndMutateRow(context, request);
      },
      request, __func__);
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigtable_internal
}  // namespace cloud
}  // namespace google
