// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/gsuiteaddons/v1/gsuiteaddons.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GSUITEADDONS_V1_MOCKS_MOCK_G_SUITE_ADD_ONS_CONNECTION_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GSUITEADDONS_V1_MOCKS_MOCK_G_SUITE_ADD_ONS_CONNECTION_H

#include "google/cloud/gsuiteaddons/v1/g_suite_add_ons_connection.h"
#include <gmock/gmock.h>

namespace google {
namespace cloud {
namespace gsuiteaddons_v1_mocks {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

/**
 * A class to mock `GSuiteAddOnsConnection`.
 *
 * Application developers may want to test their code with simulated responses,
 * including errors, from an object of type `GSuiteAddOnsClient`. To do so,
 * construct an object of type `GSuiteAddOnsClient` with an instance of this
 * class. Then use the Google Test framework functions to program the behavior
 * of this mock.
 *
 * @see [This example][bq-mock] for how to test your application with GoogleTest.
 * While the example showcases types from the BigQuery library, the underlying
 * principles apply for any pair of `*Client` and `*Connection`.
 *
 * [bq-mock]: @cloud_cpp_docs_link{bigquery,bigquery-read-mock}
 */
class MockGSuiteAddOnsConnection
    : public gsuiteaddons_v1::GSuiteAddOnsConnection {
 public:
  MOCK_METHOD(Options, options, (), (override));

  MOCK_METHOD(
      StatusOr<google::cloud::gsuiteaddons::v1::Authorization>,
      GetAuthorization,
      (google::cloud::gsuiteaddons::v1::GetAuthorizationRequest const& request),
      (override));

  MOCK_METHOD(
      StatusOr<google::cloud::gsuiteaddons::v1::Deployment>, CreateDeployment,
      (google::cloud::gsuiteaddons::v1::CreateDeploymentRequest const& request),
      (override));

  MOCK_METHOD(StatusOr<google::cloud::gsuiteaddons::v1::Deployment>,
              ReplaceDeployment,
              (google::cloud::gsuiteaddons::v1::ReplaceDeploymentRequest const&
                   request),
              (override));

  MOCK_METHOD(
      StatusOr<google::cloud::gsuiteaddons::v1::Deployment>, GetDeployment,
      (google::cloud::gsuiteaddons::v1::GetDeploymentRequest const& request),
      (override));

  MOCK_METHOD(StreamRange<google::cloud::gsuiteaddons::v1::Deployment>,
              ListDeployments,
              (google::cloud::gsuiteaddons::v1::ListDeploymentsRequest request),
              (override));

  MOCK_METHOD(
      Status, DeleteDeployment,
      (google::cloud::gsuiteaddons::v1::DeleteDeploymentRequest const& request),
      (override));

  MOCK_METHOD(Status, InstallDeployment,
              (google::cloud::gsuiteaddons::v1::InstallDeploymentRequest const&
                   request),
              (override));

  MOCK_METHOD(
      Status, UninstallDeployment,
      (google::cloud::gsuiteaddons::v1::UninstallDeploymentRequest const&
           request),
      (override));

  MOCK_METHOD(
      StatusOr<google::cloud::gsuiteaddons::v1::InstallStatus>,
      GetInstallStatus,
      (google::cloud::gsuiteaddons::v1::GetInstallStatusRequest const& request),
      (override));
};

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace gsuiteaddons_v1_mocks
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GSUITEADDONS_V1_MOCKS_MOCK_G_SUITE_ADD_ONS_CONNECTION_H
