// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/transactions.proto

#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_transactions_connection_impl.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_transactions_option_defaults.h"
#include "google/cloud/background_threads.h"
#include "google/cloud/common_options.h"
#include "google/cloud/grpc_options.h"
#include "google/cloud/internal/async_long_running_operation.h"
#include "google/cloud/internal/pagination_range.h"
#include "google/cloud/internal/retry_loop.h"
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

IssuerSwitchTransactionsConnectionImpl::IssuerSwitchTransactionsConnectionImpl(
    std::unique_ptr<google::cloud::BackgroundThreads> background,
    std::shared_ptr<
        paymentgateway_issuerswitch_v1_internal::IssuerSwitchTransactionsStub>
        stub,
    Options options)
    : background_(std::move(background)),
      stub_(std::move(stub)),
      options_(internal::MergeOptions(
          std::move(options), IssuerSwitchTransactionsConnection::options())) {}

StreamRange<
    google::cloud::paymentgateway::issuerswitch::v1::MetadataTransaction>
IssuerSwitchTransactionsConnectionImpl::ListMetadataTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ListMetadataTransactionsRequest request) {
  request.clear_page_token();
  auto& stub = stub_;
  auto retry = std::shared_ptr<paymentgateway_issuerswitch_v1::
                                   IssuerSwitchTransactionsRetryPolicy const>(
      retry_policy());
  auto backoff = std::shared_ptr<BackoffPolicy const>(backoff_policy());
  auto idempotency = idempotency_policy()->ListMetadataTransactions(request);
  char const* function_name = __func__;
  return google::cloud::internal::MakePaginationRange<StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::MetadataTransaction>>(
      std::move(request),
      [stub, retry, backoff, idempotency,
       function_name](google::cloud::paymentgateway::issuerswitch::v1::
                          ListMetadataTransactionsRequest const& r) {
        return google::cloud::internal::RetryLoop(
            retry->clone(), backoff->clone(), idempotency,
            [stub](grpc::ClientContext& context,
                   google::cloud::paymentgateway::issuerswitch::v1::
                       ListMetadataTransactionsRequest const& request) {
              return stub->ListMetadataTransactions(context, request);
            },
            r, function_name);
      },
      [](google::cloud::paymentgateway::issuerswitch::v1::
             ListMetadataTransactionsResponse r) {
        std::vector<google::cloud::paymentgateway::issuerswitch::v1::
                        MetadataTransaction>
            result(r.metadata_transactions().size());
        auto& messages = *r.mutable_metadata_transactions();
        std::move(messages.begin(), messages.end(), result.begin());
        return result;
      });
}

StreamRange<
    google::cloud::paymentgateway::issuerswitch::v1::FinancialTransaction>
IssuerSwitchTransactionsConnectionImpl::ListFinancialTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ListFinancialTransactionsRequest request) {
  request.clear_page_token();
  auto& stub = stub_;
  auto retry = std::shared_ptr<paymentgateway_issuerswitch_v1::
                                   IssuerSwitchTransactionsRetryPolicy const>(
      retry_policy());
  auto backoff = std::shared_ptr<BackoffPolicy const>(backoff_policy());
  auto idempotency = idempotency_policy()->ListFinancialTransactions(request);
  char const* function_name = __func__;
  return google::cloud::internal::MakePaginationRange<StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::FinancialTransaction>>(
      std::move(request),
      [stub, retry, backoff, idempotency,
       function_name](google::cloud::paymentgateway::issuerswitch::v1::
                          ListFinancialTransactionsRequest const& r) {
        return google::cloud::internal::RetryLoop(
            retry->clone(), backoff->clone(), idempotency,
            [stub](grpc::ClientContext& context,
                   google::cloud::paymentgateway::issuerswitch::v1::
                       ListFinancialTransactionsRequest const& request) {
              return stub->ListFinancialTransactions(context, request);
            },
            r, function_name);
      },
      [](google::cloud::paymentgateway::issuerswitch::v1::
             ListFinancialTransactionsResponse r) {
        std::vector<google::cloud::paymentgateway::issuerswitch::v1::
                        FinancialTransaction>
            result(r.financial_transactions().size());
        auto& messages = *r.mutable_financial_transactions();
        std::move(messages.begin(), messages.end(), result.begin());
        return result;
      });
}

StreamRange<google::cloud::paymentgateway::issuerswitch::v1::MandateTransaction>
IssuerSwitchTransactionsConnectionImpl::ListMandateTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ListMandateTransactionsRequest request) {
  request.clear_page_token();
  auto& stub = stub_;
  auto retry = std::shared_ptr<paymentgateway_issuerswitch_v1::
                                   IssuerSwitchTransactionsRetryPolicy const>(
      retry_policy());
  auto backoff = std::shared_ptr<BackoffPolicy const>(backoff_policy());
  auto idempotency = idempotency_policy()->ListMandateTransactions(request);
  char const* function_name = __func__;
  return google::cloud::internal::MakePaginationRange<StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::MandateTransaction>>(
      std::move(request),
      [stub, retry, backoff, idempotency,
       function_name](google::cloud::paymentgateway::issuerswitch::v1::
                          ListMandateTransactionsRequest const& r) {
        return google::cloud::internal::RetryLoop(
            retry->clone(), backoff->clone(), idempotency,
            [stub](grpc::ClientContext& context,
                   google::cloud::paymentgateway::issuerswitch::v1::
                       ListMandateTransactionsRequest const& request) {
              return stub->ListMandateTransactions(context, request);
            },
            r, function_name);
      },
      [](google::cloud::paymentgateway::issuerswitch::v1::
             ListMandateTransactionsResponse r) {
        std::vector<
            google::cloud::paymentgateway::issuerswitch::v1::MandateTransaction>
            result(r.mandate_transactions().size());
        auto& messages = *r.mutable_mandate_transactions();
        std::move(messages.begin(), messages.end(), result.begin());
        return result;
      });
}

StreamRange<
    google::cloud::paymentgateway::issuerswitch::v1::ComplaintTransaction>
IssuerSwitchTransactionsConnectionImpl::ListComplaintTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ListComplaintTransactionsRequest request) {
  request.clear_page_token();
  auto& stub = stub_;
  auto retry = std::shared_ptr<paymentgateway_issuerswitch_v1::
                                   IssuerSwitchTransactionsRetryPolicy const>(
      retry_policy());
  auto backoff = std::shared_ptr<BackoffPolicy const>(backoff_policy());
  auto idempotency = idempotency_policy()->ListComplaintTransactions(request);
  char const* function_name = __func__;
  return google::cloud::internal::MakePaginationRange<StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::ComplaintTransaction>>(
      std::move(request),
      [stub, retry, backoff, idempotency,
       function_name](google::cloud::paymentgateway::issuerswitch::v1::
                          ListComplaintTransactionsRequest const& r) {
        return google::cloud::internal::RetryLoop(
            retry->clone(), backoff->clone(), idempotency,
            [stub](grpc::ClientContext& context,
                   google::cloud::paymentgateway::issuerswitch::v1::
                       ListComplaintTransactionsRequest const& request) {
              return stub->ListComplaintTransactions(context, request);
            },
            r, function_name);
      },
      [](google::cloud::paymentgateway::issuerswitch::v1::
             ListComplaintTransactionsResponse r) {
        std::vector<google::cloud::paymentgateway::issuerswitch::v1::
                        ComplaintTransaction>
            result(r.complaint_transactions().size());
        auto& messages = *r.mutable_complaint_transactions();
        std::move(messages.begin(), messages.end(), result.begin());
        return result;
      });
}

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                    ExportFinancialTransactionsResponse>>
IssuerSwitchTransactionsConnectionImpl::ExportFinancialTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ExportFinancialTransactionsRequest const& request) {
  auto& stub = stub_;
  return google::cloud::internal::AsyncLongRunningOperation<
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportFinancialTransactionsResponse>(
      background_->cq(), request,
      [stub](google::cloud::CompletionQueue& cq,
             std::unique_ptr<grpc::ClientContext> context,
             google::cloud::paymentgateway::issuerswitch::v1::
                 ExportFinancialTransactionsRequest const& request) {
        return stub->AsyncExportFinancialTransactions(cq, std::move(context),
                                                      request);
      },
      [stub](google::cloud::CompletionQueue& cq,
             std::unique_ptr<grpc::ClientContext> context,
             google::longrunning::GetOperationRequest const& request) {
        return stub->AsyncGetOperation(cq, std::move(context), request);
      },
      [stub](google::cloud::CompletionQueue& cq,
             std::unique_ptr<grpc::ClientContext> context,
             google::longrunning::CancelOperationRequest const& request) {
        return stub->AsyncCancelOperation(cq, std::move(context), request);
      },
      &google::cloud::internal::ExtractLongRunningResultResponse<
          google::cloud::paymentgateway::issuerswitch::v1::
              ExportFinancialTransactionsResponse>,
      retry_policy(), backoff_policy(),
      idempotency_policy()->ExportFinancialTransactions(request),
      polling_policy(), __func__);
}

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                    ExportMetadataTransactionsResponse>>
IssuerSwitchTransactionsConnectionImpl::ExportMetadataTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ExportMetadataTransactionsRequest const& request) {
  auto& stub = stub_;
  return google::cloud::internal::AsyncLongRunningOperation<
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportMetadataTransactionsResponse>(
      background_->cq(), request,
      [stub](google::cloud::CompletionQueue& cq,
             std::unique_ptr<grpc::ClientContext> context,
             google::cloud::paymentgateway::issuerswitch::v1::
                 ExportMetadataTransactionsRequest const& request) {
        return stub->AsyncExportMetadataTransactions(cq, std::move(context),
                                                     request);
      },
      [stub](google::cloud::CompletionQueue& cq,
             std::unique_ptr<grpc::ClientContext> context,
             google::longrunning::GetOperationRequest const& request) {
        return stub->AsyncGetOperation(cq, std::move(context), request);
      },
      [stub](google::cloud::CompletionQueue& cq,
             std::unique_ptr<grpc::ClientContext> context,
             google::longrunning::CancelOperationRequest const& request) {
        return stub->AsyncCancelOperation(cq, std::move(context), request);
      },
      &google::cloud::internal::ExtractLongRunningResultResponse<
          google::cloud::paymentgateway::issuerswitch::v1::
              ExportMetadataTransactionsResponse>,
      retry_policy(), backoff_policy(),
      idempotency_policy()->ExportMetadataTransactions(request),
      polling_policy(), __func__);
}

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                    ExportMandateTransactionsResponse>>
IssuerSwitchTransactionsConnectionImpl::ExportMandateTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ExportMandateTransactionsRequest const& request) {
  auto& stub = stub_;
  return google::cloud::internal::AsyncLongRunningOperation<
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportMandateTransactionsResponse>(
      background_->cq(), request,
      [stub](google::cloud::CompletionQueue& cq,
             std::unique_ptr<grpc::ClientContext> context,
             google::cloud::paymentgateway::issuerswitch::v1::
                 ExportMandateTransactionsRequest const& request) {
        return stub->AsyncExportMandateTransactions(cq, std::move(context),
                                                    request);
      },
      [stub](google::cloud::CompletionQueue& cq,
             std::unique_ptr<grpc::ClientContext> context,
             google::longrunning::GetOperationRequest const& request) {
        return stub->AsyncGetOperation(cq, std::move(context), request);
      },
      [stub](google::cloud::CompletionQueue& cq,
             std::unique_ptr<grpc::ClientContext> context,
             google::longrunning::CancelOperationRequest const& request) {
        return stub->AsyncCancelOperation(cq, std::move(context), request);
      },
      &google::cloud::internal::ExtractLongRunningResultResponse<
          google::cloud::paymentgateway::issuerswitch::v1::
              ExportMandateTransactionsResponse>,
      retry_policy(), backoff_policy(),
      idempotency_policy()->ExportMandateTransactions(request),
      polling_policy(), __func__);
}

future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                    ExportComplaintTransactionsResponse>>
IssuerSwitchTransactionsConnectionImpl::ExportComplaintTransactions(
    google::cloud::paymentgateway::issuerswitch::v1::
        ExportComplaintTransactionsRequest const& request) {
  auto& stub = stub_;
  return google::cloud::internal::AsyncLongRunningOperation<
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportComplaintTransactionsResponse>(
      background_->cq(), request,
      [stub](google::cloud::CompletionQueue& cq,
             std::unique_ptr<grpc::ClientContext> context,
             google::cloud::paymentgateway::issuerswitch::v1::
                 ExportComplaintTransactionsRequest const& request) {
        return stub->AsyncExportComplaintTransactions(cq, std::move(context),
                                                      request);
      },
      [stub](google::cloud::CompletionQueue& cq,
             std::unique_ptr<grpc::ClientContext> context,
             google::longrunning::GetOperationRequest const& request) {
        return stub->AsyncGetOperation(cq, std::move(context), request);
      },
      [stub](google::cloud::CompletionQueue& cq,
             std::unique_ptr<grpc::ClientContext> context,
             google::longrunning::CancelOperationRequest const& request) {
        return stub->AsyncCancelOperation(cq, std::move(context), request);
      },
      &google::cloud::internal::ExtractLongRunningResultResponse<
          google::cloud::paymentgateway::issuerswitch::v1::
              ExportComplaintTransactionsResponse>,
      retry_policy(), backoff_policy(),
      idempotency_policy()->ExportComplaintTransactions(request),
      polling_policy(), __func__);
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1_internal
}  // namespace cloud
}  // namespace google
