// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/rules.proto

#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_rules_auth_decorator.h"
#include <google/cloud/paymentgateway/issuerswitch/v1/rules.grpc.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

IssuerSwitchRulesAuth::IssuerSwitchRulesAuth(
    std::shared_ptr<google::cloud::internal::GrpcAuthenticationStrategy> auth,
    std::shared_ptr<IssuerSwitchRulesStub> child)
    : auth_(std::move(auth)), child_(std::move(child)) {}

StatusOr<google::cloud::paymentgateway::issuerswitch::v1::ListRulesResponse>
IssuerSwitchRulesAuth::ListRules(
    grpc::ClientContext& context,
    google::cloud::paymentgateway::issuerswitch::v1::ListRulesRequest const&
        request) {
  auto status = auth_->ConfigureContext(context);
  if (!status.ok()) return status;
  return child_->ListRules(context, request);
}

StatusOr<
    google::cloud::paymentgateway::issuerswitch::v1::ListRuleMetadataResponse>
IssuerSwitchRulesAuth::ListRuleMetadata(
    grpc::ClientContext& context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ListRuleMetadataRequest const& request) {
  auto status = auth_->ConfigureContext(context);
  if (!status.ok()) return status;
  return child_->ListRuleMetadata(context, request);
}

StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
             ListRuleMetadataValuesResponse>
IssuerSwitchRulesAuth::ListRuleMetadataValues(
    grpc::ClientContext& context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ListRuleMetadataValuesRequest const& request) {
  auto status = auth_->ConfigureContext(context);
  if (!status.ok()) return status;
  return child_->ListRuleMetadataValues(context, request);
}

StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
             BatchCreateRuleMetadataValuesResponse>
IssuerSwitchRulesAuth::BatchCreateRuleMetadataValues(
    grpc::ClientContext& context,
    google::cloud::paymentgateway::issuerswitch::v1::
        BatchCreateRuleMetadataValuesRequest const& request) {
  auto status = auth_->ConfigureContext(context);
  if (!status.ok()) return status;
  return child_->BatchCreateRuleMetadataValues(context, request);
}

Status IssuerSwitchRulesAuth::BatchDeleteRuleMetadataValues(
    grpc::ClientContext& context,
    google::cloud::paymentgateway::issuerswitch::v1::
        BatchDeleteRuleMetadataValuesRequest const& request) {
  auto status = auth_->ConfigureContext(context);
  if (!status.ok()) return status;
  return child_->BatchDeleteRuleMetadataValues(context, request);
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1_internal
}  // namespace cloud
}  // namespace google
