// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/rules.proto

#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_rules_metadata_decorator.h"
#include "google/cloud/common_options.h"
#include "google/cloud/internal/api_client_header.h"
#include "google/cloud/status_or.h"
#include <google/cloud/paymentgateway/issuerswitch/v1/rules.grpc.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

IssuerSwitchRulesMetadata::IssuerSwitchRulesMetadata(
    std::shared_ptr<IssuerSwitchRulesStub> child)
    : child_(std::move(child)),
      api_client_header_(
          google::cloud::internal::ApiClientHeader("generator")) {}

StatusOr<google::cloud::paymentgateway::issuerswitch::v1::ListRulesResponse>
IssuerSwitchRulesMetadata::ListRules(
    grpc::ClientContext& context,
    google::cloud::paymentgateway::issuerswitch::v1::ListRulesRequest const&
        request) {
  SetMetadata(context, "parent=" + request.parent());
  return child_->ListRules(context, request);
}

StatusOr<
    google::cloud::paymentgateway::issuerswitch::v1::ListRuleMetadataResponse>
IssuerSwitchRulesMetadata::ListRuleMetadata(
    grpc::ClientContext& context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ListRuleMetadataRequest const& request) {
  SetMetadata(context, "parent=" + request.parent());
  return child_->ListRuleMetadata(context, request);
}

StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
             ListRuleMetadataValuesResponse>
IssuerSwitchRulesMetadata::ListRuleMetadataValues(
    grpc::ClientContext& context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ListRuleMetadataValuesRequest const& request) {
  SetMetadata(context, "parent=" + request.parent());
  return child_->ListRuleMetadataValues(context, request);
}

StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
             BatchCreateRuleMetadataValuesResponse>
IssuerSwitchRulesMetadata::BatchCreateRuleMetadataValues(
    grpc::ClientContext& context,
    google::cloud::paymentgateway::issuerswitch::v1::
        BatchCreateRuleMetadataValuesRequest const& request) {
  SetMetadata(context, "parent=" + request.parent());
  return child_->BatchCreateRuleMetadataValues(context, request);
}

Status IssuerSwitchRulesMetadata::BatchDeleteRuleMetadataValues(
    grpc::ClientContext& context,
    google::cloud::paymentgateway::issuerswitch::v1::
        BatchDeleteRuleMetadataValuesRequest const& request) {
  SetMetadata(context, "parent=" + request.parent());
  return child_->BatchDeleteRuleMetadataValues(context, request);
}

void IssuerSwitchRulesMetadata::SetMetadata(grpc::ClientContext& context,
                                            std::string const& request_params) {
  context.AddMetadata("x-goog-request-params", request_params);
  SetMetadata(context);
}

void IssuerSwitchRulesMetadata::SetMetadata(grpc::ClientContext& context) {
  context.AddMetadata("x-goog-api-client", api_client_header_);
  auto const& options = internal::CurrentOptions();
  if (options.has<UserProjectOption>()) {
    context.AddMetadata("x-goog-user-project",
                        options.get<UserProjectOption>());
  }
  auto const& authority = options.get<AuthorityOption>();
  if (!authority.empty()) context.set_authority(authority);
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1_internal
}  // namespace cloud
}  // namespace google
