// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/transactions.proto

#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_transactions_option_defaults.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_transactions_connection.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_transactions_options.h"
#include "google/cloud/internal/populate_common_options.h"
#include "google/cloud/internal/populate_grpc_options.h"
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

namespace {
auto constexpr kBackoffScaling = 2.0;
}  // namespace

Options IssuerSwitchTransactionsDefaultOptions(Options options) {
  options = google::cloud::internal::PopulateCommonOptions(
      std::move(options),
      "GOOGLE_CLOUD_CPP_ISSUER_SWITCH_TRANSACTIONS_ENDPOINT", "",
      "GOOGLE_CLOUD_CPP_ISSUER_SWITCH_TRANSACTIONS_AUTHORITY",
      "issuerswitch.googleapis.com");
  options =
      google::cloud::internal::PopulateGrpcOptions(std::move(options), "");
  if (!options.has<paymentgateway_issuerswitch_v1::
                       IssuerSwitchTransactionsRetryPolicyOption>()) {
    options.set<paymentgateway_issuerswitch_v1::
                    IssuerSwitchTransactionsRetryPolicyOption>(
        paymentgateway_issuerswitch_v1::
            IssuerSwitchTransactionsLimitedTimeRetryPolicy(
                std::chrono::minutes(30))
                .clone());
  }
  if (!options.has<paymentgateway_issuerswitch_v1::
                       IssuerSwitchTransactionsBackoffPolicyOption>()) {
    options.set<paymentgateway_issuerswitch_v1::
                    IssuerSwitchTransactionsBackoffPolicyOption>(
        ExponentialBackoffPolicy(std::chrono::seconds(1),
                                 std::chrono::minutes(5), kBackoffScaling)
            .clone());
  }
  if (!options.has<paymentgateway_issuerswitch_v1::
                       IssuerSwitchTransactionsPollingPolicyOption>()) {
    options.set<paymentgateway_issuerswitch_v1::
                    IssuerSwitchTransactionsPollingPolicyOption>(
        GenericPollingPolicy<
            paymentgateway_issuerswitch_v1::
                IssuerSwitchTransactionsRetryPolicyOption::Type,
            paymentgateway_issuerswitch_v1::
                IssuerSwitchTransactionsBackoffPolicyOption::Type>(
            options
                .get<paymentgateway_issuerswitch_v1::
                         IssuerSwitchTransactionsRetryPolicyOption>()
                ->clone(),
            options
                .get<paymentgateway_issuerswitch_v1::
                         IssuerSwitchTransactionsBackoffPolicyOption>()
                ->clone())
            .clone());
  }
  if (!options.has<
          paymentgateway_issuerswitch_v1::
              IssuerSwitchTransactionsConnectionIdempotencyPolicyOption>()) {
    options.set<paymentgateway_issuerswitch_v1::
                    IssuerSwitchTransactionsConnectionIdempotencyPolicyOption>(
        paymentgateway_issuerswitch_v1::
            MakeDefaultIssuerSwitchTransactionsConnectionIdempotencyPolicy());
  }

  return options;
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1_internal
}  // namespace cloud
}  // namespace google
