// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/rules.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_INTERNAL_ISSUER_SWITCH_RULES_AUTH_DECORATOR_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_INTERNAL_ISSUER_SWITCH_RULES_AUTH_DECORATOR_H

#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_rules_stub.h"
#include "google/cloud/internal/unified_grpc_credentials.h"
#include "google/cloud/version.h"
#include <memory>
#include <set>
#include <string>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

class IssuerSwitchRulesAuth : public IssuerSwitchRulesStub {
 public:
  ~IssuerSwitchRulesAuth() override = default;
  IssuerSwitchRulesAuth(
      std::shared_ptr<google::cloud::internal::GrpcAuthenticationStrategy> auth,
      std::shared_ptr<IssuerSwitchRulesStub> child);

  StatusOr<google::cloud::paymentgateway::issuerswitch::v1::ListRulesResponse>
  ListRules(
      grpc::ClientContext& context,
      google::cloud::paymentgateway::issuerswitch::v1::ListRulesRequest const&
          request) override;

  StatusOr<
      google::cloud::paymentgateway::issuerswitch::v1::ListRuleMetadataResponse>
  ListRuleMetadata(grpc::ClientContext& context,
                   google::cloud::paymentgateway::issuerswitch::v1::
                       ListRuleMetadataRequest const& request) override;

  StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
               ListRuleMetadataValuesResponse>
  ListRuleMetadataValues(
      grpc::ClientContext& context,
      google::cloud::paymentgateway::issuerswitch::v1::
          ListRuleMetadataValuesRequest const& request) override;

  StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
               BatchCreateRuleMetadataValuesResponse>
  BatchCreateRuleMetadataValues(
      grpc::ClientContext& context,
      google::cloud::paymentgateway::issuerswitch::v1::
          BatchCreateRuleMetadataValuesRequest const& request) override;

  Status BatchDeleteRuleMetadataValues(
      grpc::ClientContext& context,
      google::cloud::paymentgateway::issuerswitch::v1::
          BatchDeleteRuleMetadataValuesRequest const& request) override;

 private:
  std::shared_ptr<google::cloud::internal::GrpcAuthenticationStrategy> auth_;
  std::shared_ptr<IssuerSwitchRulesStub> child_;
};

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1_internal
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_INTERNAL_ISSUER_SWITCH_RULES_AUTH_DECORATOR_H
