// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/transactions.proto

#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_transactions_auth_decorator.h"
#include <google/cloud/paymentgateway/issuerswitch/v1/transactions.grpc.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

IssuerSwitchTransactionsAuth::IssuerSwitchTransactionsAuth(
    std::shared_ptr<google::cloud::internal::GrpcAuthenticationStrategy> auth,
    std::shared_ptr<IssuerSwitchTransactionsStub> child)
    : auth_(std::move(auth)), child_(std::move(child)) {}

StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
             ListMetadataTransactionsResponse>
IssuerSwitchTransactionsAuth::ListMetadataTransactions(
    grpc::ClientContext& context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ListMetadataTransactionsRequest const& request) {
  auto status = auth_->ConfigureContext(context);
  if (!status.ok()) return status;
  return child_->ListMetadataTransactions(context, request);
}

StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
             ListFinancialTransactionsResponse>
IssuerSwitchTransactionsAuth::ListFinancialTransactions(
    grpc::ClientContext& context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ListFinancialTransactionsRequest const& request) {
  auto status = auth_->ConfigureContext(context);
  if (!status.ok()) return status;
  return child_->ListFinancialTransactions(context, request);
}

StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
             ListMandateTransactionsResponse>
IssuerSwitchTransactionsAuth::ListMandateTransactions(
    grpc::ClientContext& context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ListMandateTransactionsRequest const& request) {
  auto status = auth_->ConfigureContext(context);
  if (!status.ok()) return status;
  return child_->ListMandateTransactions(context, request);
}

StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
             ListComplaintTransactionsResponse>
IssuerSwitchTransactionsAuth::ListComplaintTransactions(
    grpc::ClientContext& context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ListComplaintTransactionsRequest const& request) {
  auto status = auth_->ConfigureContext(context);
  if (!status.ok()) return status;
  return child_->ListComplaintTransactions(context, request);
}

future<StatusOr<google::longrunning::Operation>>
IssuerSwitchTransactionsAuth::AsyncExportFinancialTransactions(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<grpc::ClientContext> context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ExportFinancialTransactionsRequest const& request) {
  using ReturnType = StatusOr<google::longrunning::Operation>;
  auto& child = child_;
  return auth_->AsyncConfigureContext(std::move(context))
      .then([cq, child,
             request](future<StatusOr<std::unique_ptr<grpc::ClientContext>>>
                          f) mutable {
        auto context = f.get();
        if (!context) {
          return make_ready_future(ReturnType(std::move(context).status()));
        }
        return child->AsyncExportFinancialTransactions(cq, *std::move(context),
                                                       request);
      });
}

future<StatusOr<google::longrunning::Operation>>
IssuerSwitchTransactionsAuth::AsyncExportMetadataTransactions(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<grpc::ClientContext> context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ExportMetadataTransactionsRequest const& request) {
  using ReturnType = StatusOr<google::longrunning::Operation>;
  auto& child = child_;
  return auth_->AsyncConfigureContext(std::move(context))
      .then([cq, child,
             request](future<StatusOr<std::unique_ptr<grpc::ClientContext>>>
                          f) mutable {
        auto context = f.get();
        if (!context) {
          return make_ready_future(ReturnType(std::move(context).status()));
        }
        return child->AsyncExportMetadataTransactions(cq, *std::move(context),
                                                      request);
      });
}

future<StatusOr<google::longrunning::Operation>>
IssuerSwitchTransactionsAuth::AsyncExportMandateTransactions(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<grpc::ClientContext> context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ExportMandateTransactionsRequest const& request) {
  using ReturnType = StatusOr<google::longrunning::Operation>;
  auto& child = child_;
  return auth_->AsyncConfigureContext(std::move(context))
      .then([cq, child,
             request](future<StatusOr<std::unique_ptr<grpc::ClientContext>>>
                          f) mutable {
        auto context = f.get();
        if (!context) {
          return make_ready_future(ReturnType(std::move(context).status()));
        }
        return child->AsyncExportMandateTransactions(cq, *std::move(context),
                                                     request);
      });
}

future<StatusOr<google::longrunning::Operation>>
IssuerSwitchTransactionsAuth::AsyncExportComplaintTransactions(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<grpc::ClientContext> context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ExportComplaintTransactionsRequest const& request) {
  using ReturnType = StatusOr<google::longrunning::Operation>;
  auto& child = child_;
  return auth_->AsyncConfigureContext(std::move(context))
      .then([cq, child,
             request](future<StatusOr<std::unique_ptr<grpc::ClientContext>>>
                          f) mutable {
        auto context = f.get();
        if (!context) {
          return make_ready_future(ReturnType(std::move(context).status()));
        }
        return child->AsyncExportComplaintTransactions(cq, *std::move(context),
                                                       request);
      });
}

future<StatusOr<google::longrunning::Operation>>
IssuerSwitchTransactionsAuth::AsyncGetOperation(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<grpc::ClientContext> context,
    google::longrunning::GetOperationRequest const& request) {
  using ReturnType = StatusOr<google::longrunning::Operation>;
  auto& child = child_;
  return auth_->AsyncConfigureContext(std::move(context))
      .then([cq, child,
             request](future<StatusOr<std::unique_ptr<grpc::ClientContext>>>
                          f) mutable {
        auto context = f.get();
        if (!context) {
          return make_ready_future(ReturnType(std::move(context).status()));
        }
        return child->AsyncGetOperation(cq, *std::move(context), request);
      });
}

future<Status> IssuerSwitchTransactionsAuth::AsyncCancelOperation(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<grpc::ClientContext> context,
    google::longrunning::CancelOperationRequest const& request) {
  auto& child = child_;
  return auth_->AsyncConfigureContext(std::move(context))
      .then([cq, child,
             request](future<StatusOr<std::unique_ptr<grpc::ClientContext>>>
                          f) mutable {
        auto context = f.get();
        if (!context) return make_ready_future(std::move(context).status());
        return child->AsyncCancelOperation(cq, *std::move(context), request);
      });
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1_internal
}  // namespace cloud
}  // namespace google
