// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/rules.proto

#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_rules_stub.h"
#include "google/cloud/grpc_error_delegate.h"
#include "google/cloud/status_or.h"
#include <google/cloud/paymentgateway/issuerswitch/v1/rules.grpc.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

IssuerSwitchRulesStub::~IssuerSwitchRulesStub() = default;

StatusOr<google::cloud::paymentgateway::issuerswitch::v1::ListRulesResponse>
DefaultIssuerSwitchRulesStub::ListRules(
    grpc::ClientContext& client_context,
    google::cloud::paymentgateway::issuerswitch::v1::ListRulesRequest const&
        request) {
  google::cloud::paymentgateway::issuerswitch::v1::ListRulesResponse response;
  auto status = grpc_stub_->ListRules(&client_context, request, &response);
  if (!status.ok()) {
    return google::cloud::MakeStatusFromRpcError(status);
  }
  return response;
}

StatusOr<
    google::cloud::paymentgateway::issuerswitch::v1::ListRuleMetadataResponse>
DefaultIssuerSwitchRulesStub::ListRuleMetadata(
    grpc::ClientContext& client_context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ListRuleMetadataRequest const& request) {
  google::cloud::paymentgateway::issuerswitch::v1::ListRuleMetadataResponse
      response;
  auto status =
      grpc_stub_->ListRuleMetadata(&client_context, request, &response);
  if (!status.ok()) {
    return google::cloud::MakeStatusFromRpcError(status);
  }
  return response;
}

StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
             ListRuleMetadataValuesResponse>
DefaultIssuerSwitchRulesStub::ListRuleMetadataValues(
    grpc::ClientContext& client_context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ListRuleMetadataValuesRequest const& request) {
  google::cloud::paymentgateway::issuerswitch::v1::
      ListRuleMetadataValuesResponse response;
  auto status =
      grpc_stub_->ListRuleMetadataValues(&client_context, request, &response);
  if (!status.ok()) {
    return google::cloud::MakeStatusFromRpcError(status);
  }
  return response;
}

StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
             BatchCreateRuleMetadataValuesResponse>
DefaultIssuerSwitchRulesStub::BatchCreateRuleMetadataValues(
    grpc::ClientContext& client_context,
    google::cloud::paymentgateway::issuerswitch::v1::
        BatchCreateRuleMetadataValuesRequest const& request) {
  google::cloud::paymentgateway::issuerswitch::v1::
      BatchCreateRuleMetadataValuesResponse response;
  auto status = grpc_stub_->BatchCreateRuleMetadataValues(&client_context,
                                                          request, &response);
  if (!status.ok()) {
    return google::cloud::MakeStatusFromRpcError(status);
  }
  return response;
}

Status DefaultIssuerSwitchRulesStub::BatchDeleteRuleMetadataValues(
    grpc::ClientContext& client_context,
    google::cloud::paymentgateway::issuerswitch::v1::
        BatchDeleteRuleMetadataValuesRequest const& request) {
  google::protobuf::Empty response;
  auto status = grpc_stub_->BatchDeleteRuleMetadataValues(&client_context,
                                                          request, &response);
  if (!status.ok()) {
    return google::cloud::MakeStatusFromRpcError(status);
  }
  return google::cloud::Status();
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1_internal
}  // namespace cloud
}  // namespace google
