// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/transactions.proto

#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_transactions_metadata_decorator.h"
#include "google/cloud/common_options.h"
#include "google/cloud/internal/api_client_header.h"
#include "google/cloud/status_or.h"
#include <google/cloud/paymentgateway/issuerswitch/v1/transactions.grpc.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

IssuerSwitchTransactionsMetadata::IssuerSwitchTransactionsMetadata(
    std::shared_ptr<IssuerSwitchTransactionsStub> child)
    : child_(std::move(child)),
      api_client_header_(
          google::cloud::internal::ApiClientHeader("generator")) {}

StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
             ListMetadataTransactionsResponse>
IssuerSwitchTransactionsMetadata::ListMetadataTransactions(
    grpc::ClientContext& context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ListMetadataTransactionsRequest const& request) {
  SetMetadata(context, "parent=" + request.parent());
  return child_->ListMetadataTransactions(context, request);
}

StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
             ListFinancialTransactionsResponse>
IssuerSwitchTransactionsMetadata::ListFinancialTransactions(
    grpc::ClientContext& context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ListFinancialTransactionsRequest const& request) {
  SetMetadata(context, "parent=" + request.parent());
  return child_->ListFinancialTransactions(context, request);
}

StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
             ListMandateTransactionsResponse>
IssuerSwitchTransactionsMetadata::ListMandateTransactions(
    grpc::ClientContext& context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ListMandateTransactionsRequest const& request) {
  SetMetadata(context, "parent=" + request.parent());
  return child_->ListMandateTransactions(context, request);
}

StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
             ListComplaintTransactionsResponse>
IssuerSwitchTransactionsMetadata::ListComplaintTransactions(
    grpc::ClientContext& context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ListComplaintTransactionsRequest const& request) {
  SetMetadata(context, "parent=" + request.parent());
  return child_->ListComplaintTransactions(context, request);
}

future<StatusOr<google::longrunning::Operation>>
IssuerSwitchTransactionsMetadata::AsyncExportFinancialTransactions(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<grpc::ClientContext> context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ExportFinancialTransactionsRequest const& request) {
  SetMetadata(*context, "parent=" + request.parent());
  return child_->AsyncExportFinancialTransactions(cq, std::move(context),
                                                  request);
}

future<StatusOr<google::longrunning::Operation>>
IssuerSwitchTransactionsMetadata::AsyncExportMetadataTransactions(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<grpc::ClientContext> context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ExportMetadataTransactionsRequest const& request) {
  SetMetadata(*context, "parent=" + request.parent());
  return child_->AsyncExportMetadataTransactions(cq, std::move(context),
                                                 request);
}

future<StatusOr<google::longrunning::Operation>>
IssuerSwitchTransactionsMetadata::AsyncExportMandateTransactions(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<grpc::ClientContext> context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ExportMandateTransactionsRequest const& request) {
  SetMetadata(*context, "parent=" + request.parent());
  return child_->AsyncExportMandateTransactions(cq, std::move(context),
                                                request);
}

future<StatusOr<google::longrunning::Operation>>
IssuerSwitchTransactionsMetadata::AsyncExportComplaintTransactions(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<grpc::ClientContext> context,
    google::cloud::paymentgateway::issuerswitch::v1::
        ExportComplaintTransactionsRequest const& request) {
  SetMetadata(*context, "parent=" + request.parent());
  return child_->AsyncExportComplaintTransactions(cq, std::move(context),
                                                  request);
}

future<StatusOr<google::longrunning::Operation>>
IssuerSwitchTransactionsMetadata::AsyncGetOperation(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<grpc::ClientContext> context,
    google::longrunning::GetOperationRequest const& request) {
  SetMetadata(*context, "name=" + request.name());
  return child_->AsyncGetOperation(cq, std::move(context), request);
}

future<Status> IssuerSwitchTransactionsMetadata::AsyncCancelOperation(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<grpc::ClientContext> context,
    google::longrunning::CancelOperationRequest const& request) {
  SetMetadata(*context, "name=" + request.name());
  return child_->AsyncCancelOperation(cq, std::move(context), request);
}

void IssuerSwitchTransactionsMetadata::SetMetadata(
    grpc::ClientContext& context, std::string const& request_params) {
  context.AddMetadata("x-goog-request-params", request_params);
  SetMetadata(context);
}

void IssuerSwitchTransactionsMetadata::SetMetadata(
    grpc::ClientContext& context) {
  context.AddMetadata("x-goog-api-client", api_client_header_);
  auto const& options = internal::CurrentOptions();
  if (options.has<UserProjectOption>()) {
    context.AddMetadata("x-goog-user-project",
                        options.get<UserProjectOption>());
  }
  auto const& authority = options.get<AuthorityOption>();
  if (!authority.empty()) context.set_authority(authority);
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1_internal
}  // namespace cloud
}  // namespace google
