// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/rules.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_INTERNAL_ISSUER_SWITCH_RULES_CONNECTION_IMPL_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_INTERNAL_ISSUER_SWITCH_RULES_CONNECTION_IMPL_H

#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_rules_retry_traits.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_rules_stub.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_rules_connection.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_rules_connection_idempotency_policy.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_rules_options.h"
#include "google/cloud/background_threads.h"
#include "google/cloud/backoff_policy.h"
#include "google/cloud/options.h"
#include "google/cloud/status_or.h"
#include "google/cloud/stream_range.h"
#include "google/cloud/version.h"
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

class IssuerSwitchRulesConnectionImpl
    : public paymentgateway_issuerswitch_v1::IssuerSwitchRulesConnection {
 public:
  ~IssuerSwitchRulesConnectionImpl() override = default;

  IssuerSwitchRulesConnectionImpl(
      std::unique_ptr<google::cloud::BackgroundThreads> background,
      std::shared_ptr<
          paymentgateway_issuerswitch_v1_internal::IssuerSwitchRulesStub>
          stub,
      Options options);

  Options options() override { return options_; }

  StreamRange<google::cloud::paymentgateway::issuerswitch::v1::Rule> ListRules(
      google::cloud::paymentgateway::issuerswitch::v1::ListRulesRequest request)
      override;

  StreamRange<google::cloud::paymentgateway::issuerswitch::v1::RuleMetadata>
  ListRuleMetadata(
      google::cloud::paymentgateway::issuerswitch::v1::ListRuleMetadataRequest
          request) override;

  StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::RuleMetadataValue>
  ListRuleMetadataValues(google::cloud::paymentgateway::issuerswitch::v1::
                             ListRuleMetadataValuesRequest request) override;

  StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
               BatchCreateRuleMetadataValuesResponse>
  BatchCreateRuleMetadataValues(
      google::cloud::paymentgateway::issuerswitch::v1::
          BatchCreateRuleMetadataValuesRequest const& request) override;

  Status BatchDeleteRuleMetadataValues(
      google::cloud::paymentgateway::issuerswitch::v1::
          BatchDeleteRuleMetadataValuesRequest const& request) override;

 private:
  std::unique_ptr<paymentgateway_issuerswitch_v1::IssuerSwitchRulesRetryPolicy>
  retry_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<paymentgateway_issuerswitch_v1::
                        IssuerSwitchRulesRetryPolicyOption>()) {
      return options
          .get<paymentgateway_issuerswitch_v1::
                   IssuerSwitchRulesRetryPolicyOption>()
          ->clone();
    }
    return options_
        .get<paymentgateway_issuerswitch_v1::
                 IssuerSwitchRulesRetryPolicyOption>()
        ->clone();
  }

  std::unique_ptr<BackoffPolicy> backoff_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<paymentgateway_issuerswitch_v1::
                        IssuerSwitchRulesBackoffPolicyOption>()) {
      return options
          .get<paymentgateway_issuerswitch_v1::
                   IssuerSwitchRulesBackoffPolicyOption>()
          ->clone();
    }
    return options_
        .get<paymentgateway_issuerswitch_v1::
                 IssuerSwitchRulesBackoffPolicyOption>()
        ->clone();
  }

  std::unique_ptr<paymentgateway_issuerswitch_v1::
                      IssuerSwitchRulesConnectionIdempotencyPolicy>
  idempotency_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<paymentgateway_issuerswitch_v1::
                        IssuerSwitchRulesConnectionIdempotencyPolicyOption>()) {
      return options
          .get<paymentgateway_issuerswitch_v1::
                   IssuerSwitchRulesConnectionIdempotencyPolicyOption>()
          ->clone();
    }
    return options_
        .get<paymentgateway_issuerswitch_v1::
                 IssuerSwitchRulesConnectionIdempotencyPolicyOption>()
        ->clone();
  }

  std::unique_ptr<google::cloud::BackgroundThreads> background_;
  std::shared_ptr<
      paymentgateway_issuerswitch_v1_internal::IssuerSwitchRulesStub>
      stub_;
  Options options_;
};

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1_internal
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_INTERNAL_ISSUER_SWITCH_RULES_CONNECTION_IMPL_H
