// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/transactions.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_INTERNAL_ISSUER_SWITCH_TRANSACTIONS_LOGGING_DECORATOR_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_INTERNAL_ISSUER_SWITCH_TRANSACTIONS_LOGGING_DECORATOR_H

#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_transactions_stub.h"
#include "google/cloud/tracing_options.h"
#include "google/cloud/version.h"
#include <google/longrunning/operations.grpc.pb.h>
#include <memory>
#include <set>
#include <string>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

class IssuerSwitchTransactionsLogging : public IssuerSwitchTransactionsStub {
 public:
  ~IssuerSwitchTransactionsLogging() override = default;
  IssuerSwitchTransactionsLogging(
      std::shared_ptr<IssuerSwitchTransactionsStub> child,
      TracingOptions tracing_options, std::set<std::string> components);

  StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
               ListMetadataTransactionsResponse>
  ListMetadataTransactions(
      grpc::ClientContext& context,
      google::cloud::paymentgateway::issuerswitch::v1::
          ListMetadataTransactionsRequest const& request) override;

  StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
               ListFinancialTransactionsResponse>
  ListFinancialTransactions(
      grpc::ClientContext& context,
      google::cloud::paymentgateway::issuerswitch::v1::
          ListFinancialTransactionsRequest const& request) override;

  StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
               ListMandateTransactionsResponse>
  ListMandateTransactions(
      grpc::ClientContext& context,
      google::cloud::paymentgateway::issuerswitch::v1::
          ListMandateTransactionsRequest const& request) override;

  StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
               ListComplaintTransactionsResponse>
  ListComplaintTransactions(
      grpc::ClientContext& context,
      google::cloud::paymentgateway::issuerswitch::v1::
          ListComplaintTransactionsRequest const& request) override;

  future<StatusOr<google::longrunning::Operation>>
  AsyncExportFinancialTransactions(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<grpc::ClientContext> context,
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportFinancialTransactionsRequest const& request) override;

  future<StatusOr<google::longrunning::Operation>>
  AsyncExportMetadataTransactions(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<grpc::ClientContext> context,
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportMetadataTransactionsRequest const& request) override;

  future<StatusOr<google::longrunning::Operation>>
  AsyncExportMandateTransactions(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<grpc::ClientContext> context,
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportMandateTransactionsRequest const& request) override;

  future<StatusOr<google::longrunning::Operation>>
  AsyncExportComplaintTransactions(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<grpc::ClientContext> context,
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportComplaintTransactionsRequest const& request) override;

  future<StatusOr<google::longrunning::Operation>> AsyncGetOperation(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<grpc::ClientContext> context,
      google::longrunning::GetOperationRequest const& request) override;

  future<Status> AsyncCancelOperation(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<grpc::ClientContext> context,
      google::longrunning::CancelOperationRequest const& request) override;

 private:
  std::shared_ptr<IssuerSwitchTransactionsStub> child_;
  TracingOptions tracing_options_;
  std::set<std::string> components_;
};  // IssuerSwitchTransactionsLogging

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1_internal
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_INTERNAL_ISSUER_SWITCH_TRANSACTIONS_LOGGING_DECORATOR_H
