// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/transactions.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_INTERNAL_ISSUER_SWITCH_TRANSACTIONS_CONNECTION_IMPL_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_INTERNAL_ISSUER_SWITCH_TRANSACTIONS_CONNECTION_IMPL_H

#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_transactions_retry_traits.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_transactions_stub.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_transactions_connection.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_transactions_connection_idempotency_policy.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_transactions_options.h"
#include "google/cloud/background_threads.h"
#include "google/cloud/backoff_policy.h"
#include "google/cloud/future.h"
#include "google/cloud/options.h"
#include "google/cloud/polling_policy.h"
#include "google/cloud/status_or.h"
#include "google/cloud/stream_range.h"
#include "google/cloud/version.h"
#include <google/longrunning/operations.grpc.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

class IssuerSwitchTransactionsConnectionImpl
    : public paymentgateway_issuerswitch_v1::
          IssuerSwitchTransactionsConnection {
 public:
  ~IssuerSwitchTransactionsConnectionImpl() override = default;

  IssuerSwitchTransactionsConnectionImpl(
      std::unique_ptr<google::cloud::BackgroundThreads> background,
      std::shared_ptr<
          paymentgateway_issuerswitch_v1_internal::IssuerSwitchTransactionsStub>
          stub,
      Options options);

  Options options() override { return options_; }

  StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::MetadataTransaction>
  ListMetadataTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ListMetadataTransactionsRequest request) override;

  StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::FinancialTransaction>
  ListFinancialTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ListFinancialTransactionsRequest request) override;

  StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::MandateTransaction>
  ListMandateTransactions(google::cloud::paymentgateway::issuerswitch::v1::
                              ListMandateTransactionsRequest request) override;

  StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::ComplaintTransaction>
  ListComplaintTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ListComplaintTransactionsRequest request) override;

  future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                      ExportFinancialTransactionsResponse>>
  ExportFinancialTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportFinancialTransactionsRequest const& request) override;

  future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                      ExportMetadataTransactionsResponse>>
  ExportMetadataTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportMetadataTransactionsRequest const& request) override;

  future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                      ExportMandateTransactionsResponse>>
  ExportMandateTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportMandateTransactionsRequest const& request) override;

  future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                      ExportComplaintTransactionsResponse>>
  ExportComplaintTransactions(
      google::cloud::paymentgateway::issuerswitch::v1::
          ExportComplaintTransactionsRequest const& request) override;

 private:
  std::unique_ptr<
      paymentgateway_issuerswitch_v1::IssuerSwitchTransactionsRetryPolicy>
  retry_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<paymentgateway_issuerswitch_v1::
                        IssuerSwitchTransactionsRetryPolicyOption>()) {
      return options
          .get<paymentgateway_issuerswitch_v1::
                   IssuerSwitchTransactionsRetryPolicyOption>()
          ->clone();
    }
    return options_
        .get<paymentgateway_issuerswitch_v1::
                 IssuerSwitchTransactionsRetryPolicyOption>()
        ->clone();
  }

  std::unique_ptr<BackoffPolicy> backoff_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<paymentgateway_issuerswitch_v1::
                        IssuerSwitchTransactionsBackoffPolicyOption>()) {
      return options
          .get<paymentgateway_issuerswitch_v1::
                   IssuerSwitchTransactionsBackoffPolicyOption>()
          ->clone();
    }
    return options_
        .get<paymentgateway_issuerswitch_v1::
                 IssuerSwitchTransactionsBackoffPolicyOption>()
        ->clone();
  }

  std::unique_ptr<paymentgateway_issuerswitch_v1::
                      IssuerSwitchTransactionsConnectionIdempotencyPolicy>
  idempotency_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<
            paymentgateway_issuerswitch_v1::
                IssuerSwitchTransactionsConnectionIdempotencyPolicyOption>()) {
      return options
          .get<paymentgateway_issuerswitch_v1::
                   IssuerSwitchTransactionsConnectionIdempotencyPolicyOption>()
          ->clone();
    }
    return options_
        .get<paymentgateway_issuerswitch_v1::
                 IssuerSwitchTransactionsConnectionIdempotencyPolicyOption>()
        ->clone();
  }

  std::unique_ptr<PollingPolicy> polling_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<paymentgateway_issuerswitch_v1::
                        IssuerSwitchTransactionsPollingPolicyOption>()) {
      return options
          .get<paymentgateway_issuerswitch_v1::
                   IssuerSwitchTransactionsPollingPolicyOption>()
          ->clone();
    }
    return options_
        .get<paymentgateway_issuerswitch_v1::
                 IssuerSwitchTransactionsPollingPolicyOption>()
        ->clone();
  }

  std::unique_ptr<google::cloud::BackgroundThreads> background_;
  std::shared_ptr<
      paymentgateway_issuerswitch_v1_internal::IssuerSwitchTransactionsStub>
      stub_;
  Options options_;
};

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1_internal
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_INTERNAL_ISSUER_SWITCH_TRANSACTIONS_CONNECTION_IMPL_H
