// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/rules.proto

#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_rules_connection_impl.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_rules_option_defaults.h"
#include "google/cloud/background_threads.h"
#include "google/cloud/common_options.h"
#include "google/cloud/grpc_options.h"
#include "google/cloud/internal/pagination_range.h"
#include "google/cloud/internal/retry_loop.h"
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

IssuerSwitchRulesConnectionImpl::IssuerSwitchRulesConnectionImpl(
    std::unique_ptr<google::cloud::BackgroundThreads> background,
    std::shared_ptr<
        paymentgateway_issuerswitch_v1_internal::IssuerSwitchRulesStub>
        stub,
    Options options)
    : background_(std::move(background)),
      stub_(std::move(stub)),
      options_(internal::MergeOptions(
          std::move(options), IssuerSwitchRulesConnection::options())) {}

StreamRange<google::cloud::paymentgateway::issuerswitch::v1::Rule>
IssuerSwitchRulesConnectionImpl::ListRules(
    google::cloud::paymentgateway::issuerswitch::v1::ListRulesRequest request) {
  request.clear_page_token();
  auto& stub = stub_;
  auto retry = std::shared_ptr<
      paymentgateway_issuerswitch_v1::IssuerSwitchRulesRetryPolicy const>(
      retry_policy());
  auto backoff = std::shared_ptr<BackoffPolicy const>(backoff_policy());
  auto idempotency = idempotency_policy()->ListRules(request);
  char const* function_name = __func__;
  return google::cloud::internal::MakePaginationRange<
      StreamRange<google::cloud::paymentgateway::issuerswitch::v1::Rule>>(
      std::move(request),
      [stub, retry, backoff, idempotency,
       function_name](google::cloud::paymentgateway::issuerswitch::v1::
                          ListRulesRequest const& r) {
        return google::cloud::internal::RetryLoop(
            retry->clone(), backoff->clone(), idempotency,
            [stub](grpc::ClientContext& context,
                   google::cloud::paymentgateway::issuerswitch::v1::
                       ListRulesRequest const& request) {
              return stub->ListRules(context, request);
            },
            r, function_name);
      },
      [](google::cloud::paymentgateway::issuerswitch::v1::ListRulesResponse r) {
        std::vector<google::cloud::paymentgateway::issuerswitch::v1::Rule>
            result(r.rules().size());
        auto& messages = *r.mutable_rules();
        std::move(messages.begin(), messages.end(), result.begin());
        return result;
      });
}

StreamRange<google::cloud::paymentgateway::issuerswitch::v1::RuleMetadata>
IssuerSwitchRulesConnectionImpl::ListRuleMetadata(
    google::cloud::paymentgateway::issuerswitch::v1::ListRuleMetadataRequest
        request) {
  request.clear_page_token();
  auto& stub = stub_;
  auto retry = std::shared_ptr<
      paymentgateway_issuerswitch_v1::IssuerSwitchRulesRetryPolicy const>(
      retry_policy());
  auto backoff = std::shared_ptr<BackoffPolicy const>(backoff_policy());
  auto idempotency = idempotency_policy()->ListRuleMetadata(request);
  char const* function_name = __func__;
  return google::cloud::internal::MakePaginationRange<StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::RuleMetadata>>(
      std::move(request),
      [stub, retry, backoff, idempotency,
       function_name](google::cloud::paymentgateway::issuerswitch::v1::
                          ListRuleMetadataRequest const& r) {
        return google::cloud::internal::RetryLoop(
            retry->clone(), backoff->clone(), idempotency,
            [stub](grpc::ClientContext& context,
                   google::cloud::paymentgateway::issuerswitch::v1::
                       ListRuleMetadataRequest const& request) {
              return stub->ListRuleMetadata(context, request);
            },
            r, function_name);
      },
      [](google::cloud::paymentgateway::issuerswitch::v1::
             ListRuleMetadataResponse r) {
        std::vector<
            google::cloud::paymentgateway::issuerswitch::v1::RuleMetadata>
            result(r.rule_metadata().size());
        auto& messages = *r.mutable_rule_metadata();
        std::move(messages.begin(), messages.end(), result.begin());
        return result;
      });
}

StreamRange<google::cloud::paymentgateway::issuerswitch::v1::RuleMetadataValue>
IssuerSwitchRulesConnectionImpl::ListRuleMetadataValues(
    google::cloud::paymentgateway::issuerswitch::v1::
        ListRuleMetadataValuesRequest request) {
  request.clear_page_token();
  auto& stub = stub_;
  auto retry = std::shared_ptr<
      paymentgateway_issuerswitch_v1::IssuerSwitchRulesRetryPolicy const>(
      retry_policy());
  auto backoff = std::shared_ptr<BackoffPolicy const>(backoff_policy());
  auto idempotency = idempotency_policy()->ListRuleMetadataValues(request);
  char const* function_name = __func__;
  return google::cloud::internal::MakePaginationRange<StreamRange<
      google::cloud::paymentgateway::issuerswitch::v1::RuleMetadataValue>>(
      std::move(request),
      [stub, retry, backoff, idempotency,
       function_name](google::cloud::paymentgateway::issuerswitch::v1::
                          ListRuleMetadataValuesRequest const& r) {
        return google::cloud::internal::RetryLoop(
            retry->clone(), backoff->clone(), idempotency,
            [stub](grpc::ClientContext& context,
                   google::cloud::paymentgateway::issuerswitch::v1::
                       ListRuleMetadataValuesRequest const& request) {
              return stub->ListRuleMetadataValues(context, request);
            },
            r, function_name);
      },
      [](google::cloud::paymentgateway::issuerswitch::v1::
             ListRuleMetadataValuesResponse r) {
        std::vector<
            google::cloud::paymentgateway::issuerswitch::v1::RuleMetadataValue>
            result(r.rule_metadata_values().size());
        auto& messages = *r.mutable_rule_metadata_values();
        std::move(messages.begin(), messages.end(), result.begin());
        return result;
      });
}

StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
             BatchCreateRuleMetadataValuesResponse>
IssuerSwitchRulesConnectionImpl::BatchCreateRuleMetadataValues(
    google::cloud::paymentgateway::issuerswitch::v1::
        BatchCreateRuleMetadataValuesRequest const& request) {
  return google::cloud::internal::RetryLoop(
      retry_policy(), backoff_policy(),
      idempotency_policy()->BatchCreateRuleMetadataValues(request),
      [this](grpc::ClientContext& context,
             google::cloud::paymentgateway::issuerswitch::v1::
                 BatchCreateRuleMetadataValuesRequest const& request) {
        return stub_->BatchCreateRuleMetadataValues(context, request);
      },
      request, __func__);
}

Status IssuerSwitchRulesConnectionImpl::BatchDeleteRuleMetadataValues(
    google::cloud::paymentgateway::issuerswitch::v1::
        BatchDeleteRuleMetadataValuesRequest const& request) {
  return google::cloud::internal::RetryLoop(
      retry_policy(), backoff_policy(),
      idempotency_policy()->BatchDeleteRuleMetadataValues(request),
      [this](grpc::ClientContext& context,
             google::cloud::paymentgateway::issuerswitch::v1::
                 BatchDeleteRuleMetadataValuesRequest const& request) {
        return stub_->BatchDeleteRuleMetadataValues(context, request);
      },
      request, __func__);
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1_internal
}  // namespace cloud
}  // namespace google
