// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/resolutions.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_INTERNAL_ISSUER_SWITCH_RESOLUTIONS_CONNECTION_IMPL_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_INTERNAL_ISSUER_SWITCH_RESOLUTIONS_CONNECTION_IMPL_H

#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_resolutions_retry_traits.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/internal/issuer_switch_resolutions_stub.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_resolutions_connection.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_resolutions_connection_idempotency_policy.h"
#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_resolutions_options.h"
#include "google/cloud/background_threads.h"
#include "google/cloud/backoff_policy.h"
#include "google/cloud/future.h"
#include "google/cloud/options.h"
#include "google/cloud/polling_policy.h"
#include "google/cloud/status_or.h"
#include "google/cloud/version.h"
#include <google/longrunning/operations.grpc.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

class IssuerSwitchResolutionsConnectionImpl
    : public paymentgateway_issuerswitch_v1::IssuerSwitchResolutionsConnection {
 public:
  ~IssuerSwitchResolutionsConnectionImpl() override = default;

  IssuerSwitchResolutionsConnectionImpl(
      std::unique_ptr<google::cloud::BackgroundThreads> background,
      std::shared_ptr<
          paymentgateway_issuerswitch_v1_internal::IssuerSwitchResolutionsStub>
          stub,
      Options options);

  Options options() override { return options_; }

  future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Complaint>>
  CreateComplaint(google::cloud::paymentgateway::issuerswitch::v1::
                      CreateComplaintRequest const& request) override;

  future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Complaint>>
  ResolveComplaint(google::cloud::paymentgateway::issuerswitch::v1::
                       ResolveComplaintRequest const& request) override;

  future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Dispute>>
  CreateDispute(google::cloud::paymentgateway::issuerswitch::v1::
                    CreateDisputeRequest const& request) override;

  future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::Dispute>>
  ResolveDispute(google::cloud::paymentgateway::issuerswitch::v1::
                     ResolveDisputeRequest const& request) override;

 private:
  std::unique_ptr<
      paymentgateway_issuerswitch_v1::IssuerSwitchResolutionsRetryPolicy>
  retry_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<paymentgateway_issuerswitch_v1::
                        IssuerSwitchResolutionsRetryPolicyOption>()) {
      return options
          .get<paymentgateway_issuerswitch_v1::
                   IssuerSwitchResolutionsRetryPolicyOption>()
          ->clone();
    }
    return options_
        .get<paymentgateway_issuerswitch_v1::
                 IssuerSwitchResolutionsRetryPolicyOption>()
        ->clone();
  }

  std::unique_ptr<BackoffPolicy> backoff_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<paymentgateway_issuerswitch_v1::
                        IssuerSwitchResolutionsBackoffPolicyOption>()) {
      return options
          .get<paymentgateway_issuerswitch_v1::
                   IssuerSwitchResolutionsBackoffPolicyOption>()
          ->clone();
    }
    return options_
        .get<paymentgateway_issuerswitch_v1::
                 IssuerSwitchResolutionsBackoffPolicyOption>()
        ->clone();
  }

  std::unique_ptr<paymentgateway_issuerswitch_v1::
                      IssuerSwitchResolutionsConnectionIdempotencyPolicy>
  idempotency_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<
            paymentgateway_issuerswitch_v1::
                IssuerSwitchResolutionsConnectionIdempotencyPolicyOption>()) {
      return options
          .get<paymentgateway_issuerswitch_v1::
                   IssuerSwitchResolutionsConnectionIdempotencyPolicyOption>()
          ->clone();
    }
    return options_
        .get<paymentgateway_issuerswitch_v1::
                 IssuerSwitchResolutionsConnectionIdempotencyPolicyOption>()
        ->clone();
  }

  std::unique_ptr<PollingPolicy> polling_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<paymentgateway_issuerswitch_v1::
                        IssuerSwitchResolutionsPollingPolicyOption>()) {
      return options
          .get<paymentgateway_issuerswitch_v1::
                   IssuerSwitchResolutionsPollingPolicyOption>()
          ->clone();
    }
    return options_
        .get<paymentgateway_issuerswitch_v1::
                 IssuerSwitchResolutionsPollingPolicyOption>()
        ->clone();
  }

  std::unique_ptr<google::cloud::BackgroundThreads> background_;
  std::shared_ptr<
      paymentgateway_issuerswitch_v1_internal::IssuerSwitchResolutionsStub>
      stub_;
  Options options_;
};

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1_internal
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_INTERNAL_ISSUER_SWITCH_RESOLUTIONS_CONNECTION_IMPL_H
