// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/gsuiteaddons/v1/gsuiteaddons.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GSUITEADDONS_V1_INTERNAL_G_SUITE_ADD_ONS_TRACING_STUB_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GSUITEADDONS_V1_INTERNAL_G_SUITE_ADD_ONS_TRACING_STUB_H

#include "google/cloud/gsuiteaddons/v1/internal/g_suite_add_ons_stub.h"
#include "google/cloud/options.h"
#include "google/cloud/version.h"

namespace google {
namespace cloud {
namespace gsuiteaddons_v1_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

#ifdef GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY

class GSuiteAddOnsTracingStub : public GSuiteAddOnsStub {
 public:
  ~GSuiteAddOnsTracingStub() override = default;

  explicit GSuiteAddOnsTracingStub(std::shared_ptr<GSuiteAddOnsStub> child);

  StatusOr<google::cloud::gsuiteaddons::v1::Authorization> GetAuthorization(
      grpc::ClientContext& context,
      google::cloud::gsuiteaddons::v1::GetAuthorizationRequest const& request)
      override;

  StatusOr<google::cloud::gsuiteaddons::v1::Deployment> CreateDeployment(
      grpc::ClientContext& context,
      google::cloud::gsuiteaddons::v1::CreateDeploymentRequest const& request)
      override;

  StatusOr<google::cloud::gsuiteaddons::v1::Deployment> ReplaceDeployment(
      grpc::ClientContext& context,
      google::cloud::gsuiteaddons::v1::ReplaceDeploymentRequest const& request)
      override;

  StatusOr<google::cloud::gsuiteaddons::v1::Deployment> GetDeployment(
      grpc::ClientContext& context,
      google::cloud::gsuiteaddons::v1::GetDeploymentRequest const& request)
      override;

  StatusOr<google::cloud::gsuiteaddons::v1::ListDeploymentsResponse>
  ListDeployments(grpc::ClientContext& context,
                  google::cloud::gsuiteaddons::v1::ListDeploymentsRequest const&
                      request) override;

  Status DeleteDeployment(
      grpc::ClientContext& context,
      google::cloud::gsuiteaddons::v1::DeleteDeploymentRequest const& request)
      override;

  Status InstallDeployment(
      grpc::ClientContext& context,
      google::cloud::gsuiteaddons::v1::InstallDeploymentRequest const& request)
      override;

  Status UninstallDeployment(
      grpc::ClientContext& context,
      google::cloud::gsuiteaddons::v1::UninstallDeploymentRequest const&
          request) override;

  StatusOr<google::cloud::gsuiteaddons::v1::InstallStatus> GetInstallStatus(
      grpc::ClientContext& context,
      google::cloud::gsuiteaddons::v1::GetInstallStatusRequest const& request)
      override;

 private:
  std::shared_ptr<GSuiteAddOnsStub> child_;
};

#endif  // GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY

/**
 * Applies the tracing decorator to the given stub.
 *
 * The stub is only decorated if the library has been compiled with
 * OpenTelemetry.
 */
std::shared_ptr<GSuiteAddOnsStub> MakeGSuiteAddOnsTracingStub(
    std::shared_ptr<GSuiteAddOnsStub> stub);

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace gsuiteaddons_v1_internal
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GSUITEADDONS_V1_INTERNAL_G_SUITE_ADD_ONS_TRACING_STUB_H
