// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/paymentgateway/issuerswitch/v1/transactions.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_MOCKS_MOCK_ISSUER_SWITCH_TRANSACTIONS_CONNECTION_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_MOCKS_MOCK_ISSUER_SWITCH_TRANSACTIONS_CONNECTION_H

#include "google/cloud/paymentgateway/issuerswitch/v1/issuer_switch_transactions_connection.h"
#include <gmock/gmock.h>

namespace google {
namespace cloud {
namespace paymentgateway_issuerswitch_v1_mocks {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

/**
 * A class to mock `IssuerSwitchTransactionsConnection`.
 *
 * Application developers may want to test their code with simulated responses,
 * including errors, from an object of type `IssuerSwitchTransactionsClient`. To
 * do so, construct an object of type `IssuerSwitchTransactionsClient` with an
 * instance of this class. Then use the Google Test framework functions to
 * program the behavior of this mock.
 *
 * @see [This example][bq-mock] for how to test your application with
 * GoogleTest. While the example showcases types from the BigQuery library, the
 * underlying principles apply for any pair of `*Client` and `*Connection`.
 *
 * [bq-mock]: @googleapis_dev_link{bigquery,bigquery-read-mock.html}
 */
class MockIssuerSwitchTransactionsConnection
    : public paymentgateway_issuerswitch_v1::
          IssuerSwitchTransactionsConnection {
 public:
  MOCK_METHOD(Options, options, (), (override));

  MOCK_METHOD(
      StreamRange<
          google::cloud::paymentgateway::issuerswitch::v1::MetadataTransaction>,
      ListMetadataTransactions,
      (google::cloud::paymentgateway::issuerswitch::v1::
           ListMetadataTransactionsRequest request),
      (override));

  MOCK_METHOD(StreamRange<google::cloud::paymentgateway::issuerswitch::v1::
                              FinancialTransaction>,
              ListFinancialTransactions,
              (google::cloud::paymentgateway::issuerswitch::v1::
                   ListFinancialTransactionsRequest request),
              (override));

  MOCK_METHOD(
      StreamRange<
          google::cloud::paymentgateway::issuerswitch::v1::MandateTransaction>,
      ListMandateTransactions,
      (google::cloud::paymentgateway::issuerswitch::v1::
           ListMandateTransactionsRequest request),
      (override));

  MOCK_METHOD(StreamRange<google::cloud::paymentgateway::issuerswitch::v1::
                              ComplaintTransaction>,
              ListComplaintTransactions,
              (google::cloud::paymentgateway::issuerswitch::v1::
                   ListComplaintTransactionsRequest request),
              (override));

  MOCK_METHOD(future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                                  ExportFinancialTransactionsResponse>>,
              ExportFinancialTransactions,
              (google::cloud::paymentgateway::issuerswitch::v1::
                   ExportFinancialTransactionsRequest const& request),
              (override));

  MOCK_METHOD(future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                                  ExportMetadataTransactionsResponse>>,
              ExportMetadataTransactions,
              (google::cloud::paymentgateway::issuerswitch::v1::
                   ExportMetadataTransactionsRequest const& request),
              (override));

  MOCK_METHOD(future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                                  ExportMandateTransactionsResponse>>,
              ExportMandateTransactions,
              (google::cloud::paymentgateway::issuerswitch::v1::
                   ExportMandateTransactionsRequest const& request),
              (override));

  MOCK_METHOD(future<StatusOr<google::cloud::paymentgateway::issuerswitch::v1::
                                  ExportComplaintTransactionsResponse>>,
              ExportComplaintTransactions,
              (google::cloud::paymentgateway::issuerswitch::v1::
                   ExportComplaintTransactionsRequest const& request),
              (override));
};

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace paymentgateway_issuerswitch_v1_mocks
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_PAYMENTGATEWAY_ISSUERSWITCH_V1_MOCKS_MOCK_ISSUER_SWITCH_TRANSACTIONS_CONNECTION_H
