// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/talent/v4/company_service.proto

#include "google/cloud/talent/internal/company_stub.h"
#include "google/cloud/grpc_error_delegate.h"
#include "google/cloud/status_or.h"
#include <google/cloud/talent/v4/company_service.grpc.pb.h>
#include <memory>
// TODO : OT
#include "opentelemetry/context/propagation/global_propagator.h"
#include "opentelemetry/trace/tracer_provider.h"
#include "opentelemetry/trace/provider.h"

namespace {
class GrpcClientCarrier : public opentelemetry::context::propagation::TextMapCarrier
{
public:
  explicit GrpcClientCarrier(grpc::ClientContext *context) : context_(context) {}
  GrpcClientCarrier() = default;
  opentelemetry::nostd::string_view Get(
      opentelemetry::nostd::string_view) const noexcept override {
    return "";
  }

  void Set(opentelemetry::nostd::string_view key,
                   opentelemetry::nostd::string_view value) noexcept override
  {
    std::cout << " Client ::: Adding " << key << " " << value << "\n";
    context_->AddMetadata(key.data(), value.data());
  }

  grpc::ClientContext *context_;
};
}  // namespace

namespace google {
namespace cloud {
namespace talent_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

CompanyServiceStub::~CompanyServiceStub() = default;

StatusOr<google::cloud::talent::v4::Company>
DefaultCompanyServiceStub::CreateCompany(
    grpc::ClientContext& client_context,
    google::cloud::talent::v4::CreateCompanyRequest const& request) {
  google::cloud::talent::v4::Company response;
  auto status = grpc_stub_->CreateCompany(&client_context, request, &response);
  if (!status.ok()) {
    return google::cloud::MakeStatusFromRpcError(status);
  }
  return response;
}

StatusOr<google::cloud::talent::v4::Company>
DefaultCompanyServiceStub::GetCompany(
    grpc::ClientContext& client_context,
    google::cloud::talent::v4::GetCompanyRequest const& request) {
  google::cloud::talent::v4::Company response;
  auto status = grpc_stub_->GetCompany(&client_context, request, &response);
  if (!status.ok()) {
    return google::cloud::MakeStatusFromRpcError(status);
  }
  return response;
}

StatusOr<google::cloud::talent::v4::Company>
DefaultCompanyServiceStub::UpdateCompany(
    grpc::ClientContext& client_context,
    google::cloud::talent::v4::UpdateCompanyRequest const& request) {
  google::cloud::talent::v4::Company response;
  auto status = grpc_stub_->UpdateCompany(&client_context, request, &response);
  if (!status.ok()) {
    return google::cloud::MakeStatusFromRpcError(status);
  }
  return response;
}

Status DefaultCompanyServiceStub::DeleteCompany(
    grpc::ClientContext& client_context,
    google::cloud::talent::v4::DeleteCompanyRequest const& request) {
  google::protobuf::Empty response;
  auto status = grpc_stub_->DeleteCompany(&client_context, request, &response);
  if (!status.ok()) {
    return google::cloud::MakeStatusFromRpcError(status);
  }
  return google::cloud::Status();
}

StatusOr<google::cloud::talent::v4::ListCompaniesResponse>
DefaultCompanyServiceStub::ListCompanies(
    grpc::ClientContext& client_context,
    google::cloud::talent::v4::ListCompaniesRequest const& request) {

  // TODO : Darren : copying gRPC example from: https://github.com/open-telemetry/opentelemetry-cpp/blob/d452e8e859a8a4fd7628871383084832f9d72379/examples/grpc/client.cc#L36
  opentelemetry::trace::StartSpanOptions options;
  options.kind = opentelemetry::trace::SpanKind::kClient;

  // TODO : ip / port from peer.
  std::string peer = client_context.peer();
  //grpc_resolved_address address;
  //if (grpc_parse_uri(peer, &address)) {
  //  // PARSE
  //}


  std::string span_name = "CompanyClient/ListCompanies";
  /*
  // TODO : Not sure how to find the SemanticConventions resources... hardcoding...
  auto span = get_tracer("grpc")->StartSpan(
      span_name,
      {{SemanticConventions::RPC_SYSTEM, "grpc"},
       {SemanticConventions::RPC_SERVICE, "grpc-example.GreetService"},
       {SemanticConventions::RPC_METHOD, "Greet"},
       {SemanticConventions::NET_PEER_IP, ip},
       {SemanticConventions::NET_PEER_PORT, port}},
      options);
  */
  auto get_tracer = [](std::string tracer_name)
      -> opentelemetry::nostd::shared_ptr<opentelemetry::trace::Tracer> {
    auto provider = opentelemetry::trace::Provider::GetTracerProvider();
    return provider->GetTracer(tracer_name);
  };
  // TODO : If I don't build the dep with "HAVE_ABSEIL", the compiler cannot
  // resolve any of the StartSpan overloads. Weird. Ignoring and pressing on...
  auto span = get_tracer("talent-client")->StartSpan(
      span_name,
      {{"rpc.system", "grpc"},
       {"rpc.service", "google.cloud.talent.v4.CompanyService"},
       {"rpc.method", "ListCompanies"}},
//       {"net.peer.ip", ip},
//       {"net.peer.port", port}},
      options);

  auto scope = get_tracer("talent-client")->WithActiveSpan(span);

  // inject current context to grpc metadata
  auto current_ctx = opentelemetry::context::RuntimeContext::GetCurrent();
  GrpcClientCarrier carrier(&client_context);
  auto prop =
      opentelemetry::context::propagation::GlobalTextMapPropagator::GetGlobalPropagator();
  prop->Inject(carrier, current_ctx);


  google::cloud::talent::v4::ListCompaniesResponse response;
  auto status = grpc_stub_->ListCompanies(&client_context, request, &response);
  auto code = static_cast<int>(status.error_code());
  // span->SetAttribute(OTEL_GET_TRACE_ATTR(AttrRpcGrpcStatusCode), code);
  span->SetAttribute("rpc.grpc.status_code", code);

  if (!status.ok()) {
    span->SetStatus(opentelemetry::trace::StatusCode::kError);
    return google::cloud::MakeStatusFromRpcError(status);
  }
  span->SetStatus(opentelemetry::trace::StatusCode::kOk);
  return response;
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace talent_internal
}  // namespace cloud
}  // namespace google
