// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/bigtable/v2/bigtable.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGTABLE_BIGTABLE_CONNECTION_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGTABLE_BIGTABLE_CONNECTION_H

#include "google/cloud/bigtable/bigtable_connection_idempotency_policy.h"
#include "google/cloud/bigtable/internal/bigtable_retry_traits.h"
#include "google/cloud/bigtable/internal/bigtable_stub.h"
#include "google/cloud/backoff_policy.h"
#include "google/cloud/options.h"
#include "google/cloud/status_or.h"
#include "google/cloud/version.h"
#include <memory>

namespace google {
namespace cloud {
namespace bigtable {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

using BigtableRetryPolicy = ::google::cloud::internal::TraitBasedRetryPolicy<
    bigtable_internal::BigtableRetryTraits>;

using BigtableLimitedTimeRetryPolicy =
    ::google::cloud::internal::LimitedTimeRetryPolicy<
        bigtable_internal::BigtableRetryTraits>;

using BigtableLimitedErrorCountRetryPolicy =
    ::google::cloud::internal::LimitedErrorCountRetryPolicy<
        bigtable_internal::BigtableRetryTraits>;

class BigtableConnection {
 public:
  virtual ~BigtableConnection() = 0;

  virtual Options options() { return Options{}; }

  virtual StatusOr<google::bigtable::v2::CheckAndMutateRowResponse>
  CheckAndMutateRow(
      google::bigtable::v2::CheckAndMutateRowRequest const& request);
};

std::shared_ptr<BigtableConnection> MakeBigtableConnection(
    Options options = {});

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigtable
}  // namespace cloud
}  // namespace google

namespace google {
namespace cloud {
namespace bigtable_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

std::shared_ptr<bigtable::BigtableConnection> MakeBigtableConnection(
    std::shared_ptr<BigtableStub> stub, Options options);

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigtable_internal
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGTABLE_BIGTABLE_CONNECTION_H
