// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/bigtable/v2/bigtable.proto

#include "google/cloud/bigtable/internal/bigtable_auth_decorator.cc"
#include "google/cloud/bigtable/internal/bigtable_logging_decorator.cc"
#include "google/cloud/bigtable/internal/bigtable_metadata_decorator.cc"
#include "google/cloud/bigtable/internal/bigtable_round_robin_decorator.cc"
#include "google/cloud/bigtable/internal/bigtable_stub.cc"
#include "google/cloud/bigtable/internal/bigtable_tracing_stub.cc"
