// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/gsuiteaddons/v1/gsuiteaddons.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GSUITEADDONS_V1_G_SUITE_ADD_ONS_CLIENT_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GSUITEADDONS_V1_G_SUITE_ADD_ONS_CLIENT_H

#include "google/cloud/gsuiteaddons/v1/g_suite_add_ons_connection.h"
#include "google/cloud/future.h"
#include "google/cloud/options.h"
#include "google/cloud/polling_policy.h"
#include "google/cloud/status_or.h"
#include "google/cloud/version.h"
#include <memory>

namespace google {
namespace cloud {
namespace gsuiteaddons_v1 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

///
/// A service for managing Google Workspace Add-ons deployments.
///
/// A Google Workspace Add-on is a third-party embedded component that can be
/// installed in Google Workspace Applications like Gmail, Calendar, Drive, and
/// the Google Docs, Sheets, and Slides editors. Google Workspace Add-ons can
/// display UI cards, receive contextual information from the host application,
/// and perform actions in the host application (See:
/// https://developers.google.com/gsuite/add-ons/overview for more information).
///
/// A Google Workspace Add-on deployment resource specifies metadata about the
/// add-on, including a specification of the entry points in the host
/// application that trigger add-on executions (see:
/// https://developers.google.com/gsuite/add-ons/concepts/gsuite-manifests).
/// Add-on deployments defined via the Google Workspace Add-ons API define their
/// entrypoints using HTTPS URLs (See:
/// https://developers.google.com/gsuite/add-ons/guides/alternate-runtimes),
///
/// A Google Workspace Add-on deployment can be installed in developer mode,
/// which allows an add-on developer to test the experience an end-user would
/// see when installing and running the add-on in their G Suite applications.
/// When running in developer mode, more detailed error messages are exposed in
/// the add-on UI to aid in debugging.
///
/// A Google Workspace Add-on deployment can be published to Google Workspace
/// Marketplace, which allows other Google Workspace users to discover and
/// install the add-on.  See:
/// https://developers.google.com/gsuite/add-ons/how-tos/publish-add-on-overview
/// for details.
///
/// @par Equality
///
/// Instances of this class created via copy-construction or copy-assignment
/// always compare equal. Instances created with equal
/// `std::shared_ptr<*Connection>` objects compare equal. Objects that compare
/// equal share the same underlying resources.
///
/// @par Performance
///
/// Creating a new instance of this class is a relatively expensive operation,
/// new objects establish new connections to the service. In contrast,
/// copy-construction, move-construction, and the corresponding assignment
/// operations are relatively efficient as the copies share all underlying
/// resources.
///
/// @par Thread Safety
///
/// Concurrent access to different instances of this class, even if they compare
/// equal, is guaranteed to work. Two or more threads operating on the same
/// instance of this class is not guaranteed to work. Since copy-construction
/// and move-construction is a relatively efficient operation, consider using
/// such a copy when using this class from multiple threads.
///
class GSuiteAddOnsClient {
 public:
  explicit GSuiteAddOnsClient(
      std::shared_ptr<GSuiteAddOnsConnection> connection, Options opts = {});
  ~GSuiteAddOnsClient();

  ///@{
  /// @name Copy and move support
  GSuiteAddOnsClient(GSuiteAddOnsClient const&) = default;
  GSuiteAddOnsClient& operator=(GSuiteAddOnsClient const&) = default;
  GSuiteAddOnsClient(GSuiteAddOnsClient&&) = default;
  GSuiteAddOnsClient& operator=(GSuiteAddOnsClient&&) = default;
  ///@}

  ///@{
  /// @name Equality
  friend bool operator==(GSuiteAddOnsClient const& a,
                         GSuiteAddOnsClient const& b) {
    return a.connection_ == b.connection_;
  }
  friend bool operator!=(GSuiteAddOnsClient const& a,
                         GSuiteAddOnsClient const& b) {
    return !(a == b);
  }
  ///@}

  // clang-format off
  ///
  /// Gets the authorization information for deployments in a given project.
  ///
  /// @param name  Required. Name of the project for which to get the Google Workspace Add-ons
  ///  authorization information.
  ///  @n
  ///  Example: `projects/my_project/authorization`.
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return the result of the RPC. The response message type
  ///     ([google.cloud.gsuiteaddons.v1.Authorization])
  ///     is mapped to a C++ class using the [Protobuf mapping rules].
  ///     If the request fails, the [`StatusOr`] contains the error details.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [Long Running Operation]: https://google.aip.dev/151
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.gsuiteaddons.v1.Authorization]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L174}
  /// [google.cloud.gsuiteaddons.v1.GetAuthorizationRequest]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L160}
  ///
  // clang-format on
  StatusOr<google::cloud::gsuiteaddons::v1::Authorization> GetAuthorization(
      std::string const& name, Options opts = {});

  // clang-format off
  ///
  /// Gets the authorization information for deployments in a given project.
  ///
  /// @param request Unary RPCs, such as the one wrapped by this
  ///     function, receive a single `request` proto message which includes all
  ///     the inputs for the RPC. In this case, the proto message is a
  ///     [google.cloud.gsuiteaddons.v1.GetAuthorizationRequest].
  ///     Proto messages are converted to C++ classes by Protobuf, using the
  ///     [Protobuf mapping rules].
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return the result of the RPC. The response message type
  ///     ([google.cloud.gsuiteaddons.v1.Authorization])
  ///     is mapped to a C++ class using the [Protobuf mapping rules].
  ///     If the request fails, the [`StatusOr`] contains the error details.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [Long Running Operation]: https://google.aip.dev/151
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.gsuiteaddons.v1.Authorization]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L174}
  /// [google.cloud.gsuiteaddons.v1.GetAuthorizationRequest]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L160}
  ///
  // clang-format on
  StatusOr<google::cloud::gsuiteaddons::v1::Authorization> GetAuthorization(
      google::cloud::gsuiteaddons::v1::GetAuthorizationRequest const& request,
      Options opts = {});

  // clang-format off
  ///
  /// Creates a deployment with the specified name and configuration.
  ///
  /// @param parent  Required. Name of the project in which to create the deployment.
  ///  @n
  ///  Example: `projects/my_project`.
  /// @param deployment  Required. The deployment to create (deployment.name cannot be set).
  /// @param deployment_id  Required. The id to use for this deployment.  The full name of the created
  ///  resource will be `projects/<project_number>/deployments/<deployment_id>`.
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return the result of the RPC. The response message type
  ///     ([google.cloud.gsuiteaddons.v1.Deployment])
  ///     is mapped to a C++ class using the [Protobuf mapping rules].
  ///     If the request fails, the [`StatusOr`] contains the error details.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [Long Running Operation]: https://google.aip.dev/151
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.gsuiteaddons.v1.CreateDeploymentRequest]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L194}
  /// [google.cloud.gsuiteaddons.v1.Deployment]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L341}
  ///
  // clang-format on
  StatusOr<google::cloud::gsuiteaddons::v1::Deployment> CreateDeployment(
      std::string const& parent,
      google::cloud::gsuiteaddons::v1::Deployment const& deployment,
      std::string const& deployment_id, Options opts = {});

  // clang-format off
  ///
  /// Creates a deployment with the specified name and configuration.
  ///
  /// @param request Unary RPCs, such as the one wrapped by this
  ///     function, receive a single `request` proto message which includes all
  ///     the inputs for the RPC. In this case, the proto message is a
  ///     [google.cloud.gsuiteaddons.v1.CreateDeploymentRequest].
  ///     Proto messages are converted to C++ classes by Protobuf, using the
  ///     [Protobuf mapping rules].
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return the result of the RPC. The response message type
  ///     ([google.cloud.gsuiteaddons.v1.Deployment])
  ///     is mapped to a C++ class using the [Protobuf mapping rules].
  ///     If the request fails, the [`StatusOr`] contains the error details.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [Long Running Operation]: https://google.aip.dev/151
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.gsuiteaddons.v1.CreateDeploymentRequest]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L194}
  /// [google.cloud.gsuiteaddons.v1.Deployment]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L341}
  ///
  // clang-format on
  StatusOr<google::cloud::gsuiteaddons::v1::Deployment> CreateDeployment(
      google::cloud::gsuiteaddons::v1::CreateDeploymentRequest const& request,
      Options opts = {});

  // clang-format off
  ///
  /// Creates or replaces a deployment with the specified name.
  ///
  /// @param deployment  Required. The deployment to create or replace.
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return the result of the RPC. The response message type
  ///     ([google.cloud.gsuiteaddons.v1.Deployment])
  ///     is mapped to a C++ class using the [Protobuf mapping rules].
  ///     If the request fails, the [`StatusOr`] contains the error details.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [Long Running Operation]: https://google.aip.dev/151
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.gsuiteaddons.v1.Deployment]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L341}
  /// [google.cloud.gsuiteaddons.v1.ReplaceDeploymentRequest]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L214}
  ///
  // clang-format on
  StatusOr<google::cloud::gsuiteaddons::v1::Deployment> ReplaceDeployment(
      google::cloud::gsuiteaddons::v1::Deployment const& deployment,
      Options opts = {});

  // clang-format off
  ///
  /// Creates or replaces a deployment with the specified name.
  ///
  /// @param request Unary RPCs, such as the one wrapped by this
  ///     function, receive a single `request` proto message which includes all
  ///     the inputs for the RPC. In this case, the proto message is a
  ///     [google.cloud.gsuiteaddons.v1.ReplaceDeploymentRequest].
  ///     Proto messages are converted to C++ classes by Protobuf, using the
  ///     [Protobuf mapping rules].
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return the result of the RPC. The response message type
  ///     ([google.cloud.gsuiteaddons.v1.Deployment])
  ///     is mapped to a C++ class using the [Protobuf mapping rules].
  ///     If the request fails, the [`StatusOr`] contains the error details.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [Long Running Operation]: https://google.aip.dev/151
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.gsuiteaddons.v1.Deployment]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L341}
  /// [google.cloud.gsuiteaddons.v1.ReplaceDeploymentRequest]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L214}
  ///
  // clang-format on
  StatusOr<google::cloud::gsuiteaddons::v1::Deployment> ReplaceDeployment(
      google::cloud::gsuiteaddons::v1::ReplaceDeploymentRequest const& request,
      Options opts = {});

  // clang-format off
  ///
  /// Gets the deployment with the specified name.
  ///
  /// @param name  Required. The full resource name of the deployment to get.
  ///  @n
  ///  Example:  `projects/my_project/deployments/my_deployment`.
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return the result of the RPC. The response message type
  ///     ([google.cloud.gsuiteaddons.v1.Deployment])
  ///     is mapped to a C++ class using the [Protobuf mapping rules].
  ///     If the request fails, the [`StatusOr`] contains the error details.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [Long Running Operation]: https://google.aip.dev/151
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.gsuiteaddons.v1.Deployment]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L341}
  /// [google.cloud.gsuiteaddons.v1.GetDeploymentRequest]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L220}
  ///
  // clang-format on
  StatusOr<google::cloud::gsuiteaddons::v1::Deployment> GetDeployment(
      std::string const& name, Options opts = {});

  // clang-format off
  ///
  /// Gets the deployment with the specified name.
  ///
  /// @param request Unary RPCs, such as the one wrapped by this
  ///     function, receive a single `request` proto message which includes all
  ///     the inputs for the RPC. In this case, the proto message is a
  ///     [google.cloud.gsuiteaddons.v1.GetDeploymentRequest].
  ///     Proto messages are converted to C++ classes by Protobuf, using the
  ///     [Protobuf mapping rules].
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return the result of the RPC. The response message type
  ///     ([google.cloud.gsuiteaddons.v1.Deployment])
  ///     is mapped to a C++ class using the [Protobuf mapping rules].
  ///     If the request fails, the [`StatusOr`] contains the error details.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [Long Running Operation]: https://google.aip.dev/151
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.gsuiteaddons.v1.Deployment]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L341}
  /// [google.cloud.gsuiteaddons.v1.GetDeploymentRequest]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L220}
  ///
  // clang-format on
  StatusOr<google::cloud::gsuiteaddons::v1::Deployment> GetDeployment(
      google::cloud::gsuiteaddons::v1::GetDeploymentRequest const& request,
      Options opts = {});

  // clang-format off
  ///
  /// Lists all deployments in a particular project.
  ///
  /// @param parent  Required. Name of the project in which to create the deployment.
  ///  @n
  ///  Example: `projects/my_project`.
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return a [StreamRange](@ref google::cloud::StreamRange)
  ///     to iterate of the results. See the documentation of this type for
  ///     details. In brief, this class has `begin()` and `end()` member
  ///     functions returning a iterator class meeting the
  ///     [input iterator requirements]. The value type for this iterator is a
  ///     [`StatusOr`] as the iteration may fail even after some values are
  ///     retrieved successfully, for example, if there is a network disconnect.
  ///     An empty set of results does not indicate an error, it indicates
  ///     that there are no resources meeting the request criteria.
  ///     On a successful iteration the `StatusOr<T>` contains elements of type
  ///     [google.cloud.gsuiteaddons.v1.Deployment], or rather,
  ///     the C++ class generated by Protobuf from that type. Please consult the
  ///     Protobuf documentation for details on the [Protobuf mapping rules].
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [Long Running Operation]: https://google.aip.dev/151
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.gsuiteaddons.v1.Deployment]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L341}
  /// [google.cloud.gsuiteaddons.v1.ListDeploymentsRequest]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L233}
  ///
  // clang-format on
  StreamRange<google::cloud::gsuiteaddons::v1::Deployment> ListDeployments(
      std::string const& parent, Options opts = {});

  // clang-format off
  ///
  /// Lists all deployments in a particular project.
  ///
  /// @param request Unary RPCs, such as the one wrapped by this
  ///     function, receive a single `request` proto message which includes all
  ///     the inputs for the RPC. In this case, the proto message is a
  ///     [google.cloud.gsuiteaddons.v1.ListDeploymentsRequest].
  ///     Proto messages are converted to C++ classes by Protobuf, using the
  ///     [Protobuf mapping rules].
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return a [StreamRange](@ref google::cloud::StreamRange)
  ///     to iterate of the results. See the documentation of this type for
  ///     details. In brief, this class has `begin()` and `end()` member
  ///     functions returning a iterator class meeting the
  ///     [input iterator requirements]. The value type for this iterator is a
  ///     [`StatusOr`] as the iteration may fail even after some values are
  ///     retrieved successfully, for example, if there is a network disconnect.
  ///     An empty set of results does not indicate an error, it indicates
  ///     that there are no resources meeting the request criteria.
  ///     On a successful iteration the `StatusOr<T>` contains elements of type
  ///     [google.cloud.gsuiteaddons.v1.Deployment], or rather,
  ///     the C++ class generated by Protobuf from that type. Please consult the
  ///     Protobuf documentation for details on the [Protobuf mapping rules].
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [Long Running Operation]: https://google.aip.dev/151
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.gsuiteaddons.v1.Deployment]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L341}
  /// [google.cloud.gsuiteaddons.v1.ListDeploymentsRequest]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L233}
  ///
  // clang-format on
  StreamRange<google::cloud::gsuiteaddons::v1::Deployment> ListDeployments(
      google::cloud::gsuiteaddons::v1::ListDeploymentsRequest request,
      Options opts = {});

  // clang-format off
  ///
  /// Deletes the deployment with the given name.
  ///
  /// @param name  Required. The full resource name of the deployment to delete.
  ///  @n
  ///  Example:  `projects/my_project/deployments/my_deployment`.
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return a [`Status`] object. If the request failed, the
  ///     status contains the details of the failure.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [Long Running Operation]: https://google.aip.dev/151
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.gsuiteaddons.v1.DeleteDeploymentRequest]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L269}
  ///
  // clang-format on
  Status DeleteDeployment(std::string const& name, Options opts = {});

  // clang-format off
  ///
  /// Deletes the deployment with the given name.
  ///
  /// @param request Unary RPCs, such as the one wrapped by this
  ///     function, receive a single `request` proto message which includes all
  ///     the inputs for the RPC. In this case, the proto message is a
  ///     [google.cloud.gsuiteaddons.v1.DeleteDeploymentRequest].
  ///     Proto messages are converted to C++ classes by Protobuf, using the
  ///     [Protobuf mapping rules].
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return a [`Status`] object. If the request failed, the
  ///     status contains the details of the failure.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [Long Running Operation]: https://google.aip.dev/151
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.gsuiteaddons.v1.DeleteDeploymentRequest]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L269}
  ///
  // clang-format on
  Status DeleteDeployment(
      google::cloud::gsuiteaddons::v1::DeleteDeploymentRequest const& request,
      Options opts = {});

  // clang-format off
  ///
  /// Installs a deployment in developer mode.
  /// See:
  /// https://developers.google.com/gsuite/add-ons/how-tos/testing-gsuite-addons.
  ///
  /// @param name  Required. The full resource name of the deployment to install.
  ///  @n
  ///  Example:  `projects/my_project/deployments/my_deployment`.
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return a [`Status`] object. If the request failed, the
  ///     status contains the details of the failure.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [Long Running Operation]: https://google.aip.dev/151
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.gsuiteaddons.v1.InstallDeploymentRequest]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L286}
  ///
  // clang-format on
  Status InstallDeployment(std::string const& name, Options opts = {});

  // clang-format off
  ///
  /// Installs a deployment in developer mode.
  /// See:
  /// https://developers.google.com/gsuite/add-ons/how-tos/testing-gsuite-addons.
  ///
  /// @param request Unary RPCs, such as the one wrapped by this
  ///     function, receive a single `request` proto message which includes all
  ///     the inputs for the RPC. In this case, the proto message is a
  ///     [google.cloud.gsuiteaddons.v1.InstallDeploymentRequest].
  ///     Proto messages are converted to C++ classes by Protobuf, using the
  ///     [Protobuf mapping rules].
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return a [`Status`] object. If the request failed, the
  ///     status contains the details of the failure.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [Long Running Operation]: https://google.aip.dev/151
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.gsuiteaddons.v1.InstallDeploymentRequest]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L286}
  ///
  // clang-format on
  Status InstallDeployment(
      google::cloud::gsuiteaddons::v1::InstallDeploymentRequest const& request,
      Options opts = {});

  // clang-format off
  ///
  /// Uninstalls a developer mode deployment.
  /// See:
  /// https://developers.google.com/gsuite/add-ons/how-tos/testing-gsuite-addons.
  ///
  /// @param name  Required. The full resource name of the deployment to install.
  ///  @n
  ///  Example:  `projects/my_project/deployments/my_deployment`.
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return a [`Status`] object. If the request failed, the
  ///     status contains the details of the failure.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [Long Running Operation]: https://google.aip.dev/151
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.gsuiteaddons.v1.UninstallDeploymentRequest]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L299}
  ///
  // clang-format on
  Status UninstallDeployment(std::string const& name, Options opts = {});

  // clang-format off
  ///
  /// Uninstalls a developer mode deployment.
  /// See:
  /// https://developers.google.com/gsuite/add-ons/how-tos/testing-gsuite-addons.
  ///
  /// @param request Unary RPCs, such as the one wrapped by this
  ///     function, receive a single `request` proto message which includes all
  ///     the inputs for the RPC. In this case, the proto message is a
  ///     [google.cloud.gsuiteaddons.v1.UninstallDeploymentRequest].
  ///     Proto messages are converted to C++ classes by Protobuf, using the
  ///     [Protobuf mapping rules].
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return a [`Status`] object. If the request failed, the
  ///     status contains the details of the failure.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [Long Running Operation]: https://google.aip.dev/151
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.gsuiteaddons.v1.UninstallDeploymentRequest]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L299}
  ///
  // clang-format on
  Status UninstallDeployment(
      google::cloud::gsuiteaddons::v1::UninstallDeploymentRequest const&
          request,
      Options opts = {});

  // clang-format off
  ///
  /// Fetches the install status of a developer mode deployment.
  ///
  /// @param name  Required. The full resource name of the deployment.
  ///  @n
  ///  Example:  `projects/my_project/deployments/my_deployment/installStatus`.
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return the result of the RPC. The response message type
  ///     ([google.cloud.gsuiteaddons.v1.InstallStatus])
  ///     is mapped to a C++ class using the [Protobuf mapping rules].
  ///     If the request fails, the [`StatusOr`] contains the error details.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [Long Running Operation]: https://google.aip.dev/151
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.gsuiteaddons.v1.GetInstallStatusRequest]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L312}
  /// [google.cloud.gsuiteaddons.v1.InstallStatus]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L325}
  ///
  // clang-format on
  StatusOr<google::cloud::gsuiteaddons::v1::InstallStatus> GetInstallStatus(
      std::string const& name, Options opts = {});

  // clang-format off
  ///
  /// Fetches the install status of a developer mode deployment.
  ///
  /// @param request Unary RPCs, such as the one wrapped by this
  ///     function, receive a single `request` proto message which includes all
  ///     the inputs for the RPC. In this case, the proto message is a
  ///     [google.cloud.gsuiteaddons.v1.GetInstallStatusRequest].
  ///     Proto messages are converted to C++ classes by Protobuf, using the
  ///     [Protobuf mapping rules].
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return the result of the RPC. The response message type
  ///     ([google.cloud.gsuiteaddons.v1.InstallStatus])
  ///     is mapped to a C++ class using the [Protobuf mapping rules].
  ///     If the request fails, the [`StatusOr`] contains the error details.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [Long Running Operation]: https://google.aip.dev/151
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.gsuiteaddons.v1.GetInstallStatusRequest]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L312}
  /// [google.cloud.gsuiteaddons.v1.InstallStatus]: @googleapis_reference_link{google/cloud/gsuiteaddons/v1/gsuiteaddons.proto#L325}
  ///
  // clang-format on
  StatusOr<google::cloud::gsuiteaddons::v1::InstallStatus> GetInstallStatus(
      google::cloud::gsuiteaddons::v1::GetInstallStatusRequest const& request,
      Options opts = {});

 private:
  std::shared_ptr<GSuiteAddOnsConnection> connection_;
  Options options_;
};

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace gsuiteaddons_v1
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GSUITEADDONS_V1_G_SUITE_ADD_ONS_CLIENT_H
