// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/gsuiteaddons/v1/gsuiteaddons.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GSUITEADDONS_V1_G_SUITE_ADD_ONS_CONNECTION_IDEMPOTENCY_POLICY_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GSUITEADDONS_V1_G_SUITE_ADD_ONS_CONNECTION_IDEMPOTENCY_POLICY_H

#include "google/cloud/idempotency.h"
#include "google/cloud/version.h"
#include <google/cloud/gsuiteaddons/v1/gsuiteaddons.grpc.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace gsuiteaddons_v1 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

class GSuiteAddOnsConnectionIdempotencyPolicy {
 public:
  virtual ~GSuiteAddOnsConnectionIdempotencyPolicy();

  /// Create a new copy of this object.
  virtual std::unique_ptr<GSuiteAddOnsConnectionIdempotencyPolicy> clone()
      const;

  virtual google::cloud::Idempotency GetAuthorization(
      google::cloud::gsuiteaddons::v1::GetAuthorizationRequest const& request);

  virtual google::cloud::Idempotency CreateDeployment(
      google::cloud::gsuiteaddons::v1::CreateDeploymentRequest const& request);

  virtual google::cloud::Idempotency ReplaceDeployment(
      google::cloud::gsuiteaddons::v1::ReplaceDeploymentRequest const& request);

  virtual google::cloud::Idempotency GetDeployment(
      google::cloud::gsuiteaddons::v1::GetDeploymentRequest const& request);

  virtual google::cloud::Idempotency ListDeployments(
      google::cloud::gsuiteaddons::v1::ListDeploymentsRequest request);

  virtual google::cloud::Idempotency DeleteDeployment(
      google::cloud::gsuiteaddons::v1::DeleteDeploymentRequest const& request);

  virtual google::cloud::Idempotency InstallDeployment(
      google::cloud::gsuiteaddons::v1::InstallDeploymentRequest const& request);

  virtual google::cloud::Idempotency UninstallDeployment(
      google::cloud::gsuiteaddons::v1::UninstallDeploymentRequest const&
          request);

  virtual google::cloud::Idempotency GetInstallStatus(
      google::cloud::gsuiteaddons::v1::GetInstallStatusRequest const& request);
};

std::unique_ptr<GSuiteAddOnsConnectionIdempotencyPolicy>
MakeDefaultGSuiteAddOnsConnectionIdempotencyPolicy();

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace gsuiteaddons_v1
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GSUITEADDONS_V1_G_SUITE_ADD_ONS_CONNECTION_IDEMPOTENCY_POLICY_H
