// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/gsuiteaddons/v1/gsuiteaddons.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GSUITEADDONS_V1_G_SUITE_ADD_ONS_CONNECTION_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GSUITEADDONS_V1_G_SUITE_ADD_ONS_CONNECTION_H

#include "google/cloud/gsuiteaddons/v1/g_suite_add_ons_connection_idempotency_policy.h"
#include "google/cloud/gsuiteaddons/v1/internal/g_suite_add_ons_retry_traits.h"
#include "google/cloud/backoff_policy.h"
#include "google/cloud/internal/retry_policy_impl.h"
#include "google/cloud/options.h"
#include "google/cloud/status_or.h"
#include "google/cloud/stream_range.h"
#include "google/cloud/version.h"
#include <google/cloud/gsuiteaddons/v1/gsuiteaddons.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace gsuiteaddons_v1 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

/// The retry policy for `GSuiteAddOnsConnection`.
class GSuiteAddOnsRetryPolicy : public ::google::cloud::RetryPolicy {
 public:
  /// Creates a new instance of the policy, reset to the initial state.
  virtual std::unique_ptr<GSuiteAddOnsRetryPolicy> clone() const = 0;
};

/**
 * A retry policy for `GSuiteAddOnsConnection` based on counting errors.
 *
 * This policy stops retrying if:
 * - An RPC returns a non-transient error.
 * - More than a prescribed number of transient failures is detected.
 *
 * In this class the following status codes are treated as transient errors:
 * - [`kUnavailable`](@ref google::cloud::StatusCode)
 */
class GSuiteAddOnsLimitedErrorCountRetryPolicy
    : public GSuiteAddOnsRetryPolicy {
 public:
  /**
   * Create an instance that tolerates up to @p maximum_failures transient
   * errors.
   *
   * @note Disable the retry loop by providing an instance of this policy with
   *     @p maximum_failures == 0.
   */
  explicit GSuiteAddOnsLimitedErrorCountRetryPolicy(int maximum_failures)
      : impl_(maximum_failures) {}

  GSuiteAddOnsLimitedErrorCountRetryPolicy(
      GSuiteAddOnsLimitedErrorCountRetryPolicy&& rhs) noexcept
      : GSuiteAddOnsLimitedErrorCountRetryPolicy(rhs.maximum_failures()) {}
  GSuiteAddOnsLimitedErrorCountRetryPolicy(
      GSuiteAddOnsLimitedErrorCountRetryPolicy const& rhs) noexcept
      : GSuiteAddOnsLimitedErrorCountRetryPolicy(rhs.maximum_failures()) {}

  int maximum_failures() const { return impl_.maximum_failures(); }

  bool OnFailure(Status const& status) override {
    return impl_.OnFailure(status);
  }
  bool IsExhausted() const override { return impl_.IsExhausted(); }
  bool IsPermanentFailure(Status const& status) const override {
    return impl_.IsPermanentFailure(status);
  }
  std::unique_ptr<GSuiteAddOnsRetryPolicy> clone() const override {
    return std::make_unique<GSuiteAddOnsLimitedErrorCountRetryPolicy>(
        maximum_failures());
  }

  // This is provided only for backwards compatibility.
  using BaseType = GSuiteAddOnsRetryPolicy;

 private:
  google::cloud::internal::LimitedErrorCountRetryPolicy<
      gsuiteaddons_v1_internal::GSuiteAddOnsRetryTraits>
      impl_;
};

/**
 * A retry policy for `GSuiteAddOnsConnection` based on elapsed time.
 *
 * This policy stops retrying if:
 * - An RPC returns a non-transient error.
 * - The elapsed time in the retry loop exceeds a prescribed duration.
 *
 * In this class the following status codes are treated as transient errors:
 * - [`kUnavailable`](@ref google::cloud::StatusCode)
 */
class GSuiteAddOnsLimitedTimeRetryPolicy : public GSuiteAddOnsRetryPolicy {
 public:
  /**
   * Constructor given a `std::chrono::duration<>` object.
   *
   * @tparam DurationRep a placeholder to match the `Rep` tparam for @p
   *     duration's type. The semantics of this template parameter are
   *     documented in `std::chrono::duration<>`. In brief, the underlying
   *     arithmetic type used to store the number of ticks. For our purposes it
   *     is simply a formal parameter.
   * @tparam DurationPeriod a placeholder to match the `Period` tparam for @p
   *     duration's type. The semantics of this template parameter are
   *     documented in `std::chrono::duration<>`. In brief, the length of the
   *     tick in seconds, expressed as a `std::ratio<>`. For our purposes it is
   *     simply a formal parameter.
   * @param maximum_duration the maximum time allowed before the policy expires.
   *     While the application can express this time in any units they desire,
   *     the class truncates to milliseconds.
   *
   * @see https://en.cppreference.com/w/cpp/chrono/duration for more information
   *     about `std::chrono::duration`.
   */
  template <typename DurationRep, typename DurationPeriod>
  explicit GSuiteAddOnsLimitedTimeRetryPolicy(
      std::chrono::duration<DurationRep, DurationPeriod> maximum_duration)
      : impl_(maximum_duration) {}

  GSuiteAddOnsLimitedTimeRetryPolicy(
      GSuiteAddOnsLimitedTimeRetryPolicy&& rhs) noexcept
      : GSuiteAddOnsLimitedTimeRetryPolicy(rhs.maximum_duration()) {}
  GSuiteAddOnsLimitedTimeRetryPolicy(
      GSuiteAddOnsLimitedTimeRetryPolicy const& rhs) noexcept
      : GSuiteAddOnsLimitedTimeRetryPolicy(rhs.maximum_duration()) {}

  std::chrono::milliseconds maximum_duration() const {
    return impl_.maximum_duration();
  }

  bool OnFailure(Status const& status) override {
    return impl_.OnFailure(status);
  }
  bool IsExhausted() const override { return impl_.IsExhausted(); }
  bool IsPermanentFailure(Status const& status) const override {
    return impl_.IsPermanentFailure(status);
  }
  std::unique_ptr<GSuiteAddOnsRetryPolicy> clone() const override {
    return std::make_unique<GSuiteAddOnsLimitedTimeRetryPolicy>(
        maximum_duration());
  }

  // This is provided only for backwards compatibility.
  using BaseType = GSuiteAddOnsRetryPolicy;

 private:
  google::cloud::internal::LimitedTimeRetryPolicy<
      gsuiteaddons_v1_internal::GSuiteAddOnsRetryTraits>
      impl_;
};

/**
 * The `GSuiteAddOnsConnection` object for `GSuiteAddOnsClient`.
 *
 * This interface defines virtual methods for each of the user-facing overload
 * sets in `GSuiteAddOnsClient`. This allows users to inject custom behavior
 * (e.g., with a Google Mock object) when writing tests that use objects of type
 * `GSuiteAddOnsClient`.
 *
 * To create a concrete instance, see `MakeGSuiteAddOnsConnection()`.
 *
 * For mocking, see `gsuiteaddons_v1_mocks::MockGSuiteAddOnsConnection`.
 */
class GSuiteAddOnsConnection {
 public:
  virtual ~GSuiteAddOnsConnection() = 0;

  virtual Options options() { return Options{}; }

  virtual StatusOr<google::cloud::gsuiteaddons::v1::Authorization>
  GetAuthorization(
      google::cloud::gsuiteaddons::v1::GetAuthorizationRequest const& request);

  virtual StatusOr<google::cloud::gsuiteaddons::v1::Deployment>
  CreateDeployment(
      google::cloud::gsuiteaddons::v1::CreateDeploymentRequest const& request);

  virtual StatusOr<google::cloud::gsuiteaddons::v1::Deployment>
  ReplaceDeployment(
      google::cloud::gsuiteaddons::v1::ReplaceDeploymentRequest const& request);

  virtual StatusOr<google::cloud::gsuiteaddons::v1::Deployment> GetDeployment(
      google::cloud::gsuiteaddons::v1::GetDeploymentRequest const& request);

  virtual StreamRange<google::cloud::gsuiteaddons::v1::Deployment>
  ListDeployments(
      google::cloud::gsuiteaddons::v1::ListDeploymentsRequest request);

  virtual Status DeleteDeployment(
      google::cloud::gsuiteaddons::v1::DeleteDeploymentRequest const& request);

  virtual Status InstallDeployment(
      google::cloud::gsuiteaddons::v1::InstallDeploymentRequest const& request);

  virtual Status UninstallDeployment(
      google::cloud::gsuiteaddons::v1::UninstallDeploymentRequest const&
          request);

  virtual StatusOr<google::cloud::gsuiteaddons::v1::InstallStatus>
  GetInstallStatus(
      google::cloud::gsuiteaddons::v1::GetInstallStatusRequest const& request);
};

/**
 * A factory function to construct an object of type `GSuiteAddOnsConnection`.
 *
 * The returned connection object should not be used directly; instead it
 * should be passed as an argument to the constructor of GSuiteAddOnsClient.
 *
 * The optional @p options argument may be used to configure aspects of the
 * returned `GSuiteAddOnsConnection`. Expected options are any of the types in
 * the following option lists:
 *
 * - `google::cloud::CommonOptionList`
 * - `google::cloud::GrpcOptionList`
 * - `google::cloud::UnifiedCredentialsOptionList`
 * - `google::cloud::gsuiteaddons_v1::GSuiteAddOnsPolicyOptionList`
 *
 * @note Unexpected options will be ignored. To log unexpected options instead,
 *     set `GOOGLE_CLOUD_CPP_ENABLE_CLOG=yes` in the environment.
 *
 * @param options (optional) Configure the `GSuiteAddOnsConnection` created by
 * this function.
 */
std::shared_ptr<GSuiteAddOnsConnection> MakeGSuiteAddOnsConnection(
    Options options = {});

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace gsuiteaddons_v1
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GSUITEADDONS_V1_G_SUITE_ADD_ONS_CONNECTION_H
