// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/gsuiteaddons/v1/gsuiteaddons.proto

#include "google/cloud/gsuiteaddons/v1/g_suite_add_ons_connection_idempotency_policy.h"
#include <memory>

namespace google {
namespace cloud {
namespace gsuiteaddons_v1 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

using ::google::cloud::Idempotency;

GSuiteAddOnsConnectionIdempotencyPolicy::
    ~GSuiteAddOnsConnectionIdempotencyPolicy() = default;

std::unique_ptr<GSuiteAddOnsConnectionIdempotencyPolicy>
GSuiteAddOnsConnectionIdempotencyPolicy::clone() const {
  return std::make_unique<GSuiteAddOnsConnectionIdempotencyPolicy>(*this);
}

Idempotency GSuiteAddOnsConnectionIdempotencyPolicy::GetAuthorization(
    google::cloud::gsuiteaddons::v1::GetAuthorizationRequest const&) {
  return Idempotency::kIdempotent;
}

Idempotency GSuiteAddOnsConnectionIdempotencyPolicy::CreateDeployment(
    google::cloud::gsuiteaddons::v1::CreateDeploymentRequest const&) {
  return Idempotency::kNonIdempotent;
}

Idempotency GSuiteAddOnsConnectionIdempotencyPolicy::ReplaceDeployment(
    google::cloud::gsuiteaddons::v1::ReplaceDeploymentRequest const&) {
  return Idempotency::kIdempotent;
}

Idempotency GSuiteAddOnsConnectionIdempotencyPolicy::GetDeployment(
    google::cloud::gsuiteaddons::v1::GetDeploymentRequest const&) {
  return Idempotency::kIdempotent;
}

Idempotency GSuiteAddOnsConnectionIdempotencyPolicy::ListDeployments(
    google::cloud::gsuiteaddons::v1::ListDeploymentsRequest) {  // NOLINT
  return Idempotency::kIdempotent;
}

Idempotency GSuiteAddOnsConnectionIdempotencyPolicy::DeleteDeployment(
    google::cloud::gsuiteaddons::v1::DeleteDeploymentRequest const&) {
  return Idempotency::kNonIdempotent;
}

Idempotency GSuiteAddOnsConnectionIdempotencyPolicy::InstallDeployment(
    google::cloud::gsuiteaddons::v1::InstallDeploymentRequest const&) {
  return Idempotency::kNonIdempotent;
}

Idempotency GSuiteAddOnsConnectionIdempotencyPolicy::UninstallDeployment(
    google::cloud::gsuiteaddons::v1::UninstallDeploymentRequest const&) {
  return Idempotency::kNonIdempotent;
}

Idempotency GSuiteAddOnsConnectionIdempotencyPolicy::GetInstallStatus(
    google::cloud::gsuiteaddons::v1::GetInstallStatusRequest const&) {
  return Idempotency::kIdempotent;
}

std::unique_ptr<GSuiteAddOnsConnectionIdempotencyPolicy>
MakeDefaultGSuiteAddOnsConnectionIdempotencyPolicy() {
  return std::make_unique<GSuiteAddOnsConnectionIdempotencyPolicy>();
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace gsuiteaddons_v1
}  // namespace cloud
}  // namespace google
